all: run

run:
	: HINT :
	: HINT :
	: HINT :   For Nitros9 Level 1, type 'c1' [ or 'ce6' to debug ]
	: HINT :
	: HINT :   For Nitros9 Level 2, type 'c2' [ or 'ce7' to debug ]
	: HINT :
	: HINT :
	../generated/tconsole.linux-amd64.exe 2>/tmp/log -disks '../generated/disk0,../generated/level1.dsk,../generated/level2.dsk,../generated/disk3,../generated/disk4,../generated/disk5,../generated/disk6,../generated/disk7'  -borges /tmp/borges
