//XXX//go:build level1
//XXX// +build level1

package main

// This file was generated by scrape_os9_symbols

const (
	L1_A_AciaP     = 0xFF68 // A.AciaP
	L1_A_ModP      = 0xFF6C // A.ModP
	L1_A_TermV     = 0xFFC0 // A.TermV
	L1_A_V1        = 0xFFC1 // A.V1
	L1_A_V2        = 0xFFC2 // A.V2
	L1_A_V3        = 0xFFC3 // A.V3
	L1_A_V4        = 0xFFC4 // A.V4
	L1_A_V5        = 0xFFC5 // A.V5
	L1_A_V6        = 0xFFC6 // A.V6
	L1_A_V7        = 0xFFC7 // A.V7
	L1_Bt_Sec      = 0x0000 // Bt.Sec
	L1_Bt_Size     = 0x1080 // Bt.Size
	L1_Bt_Start    = 0xEE00 // Bt.Start
	L1_Bt_Track    = 0x0022 // Bt.Track
	L1_C_BELL      = 0x0007 // C$BELL
	L1_C_BSP       = 0x0008 // C$BSP
	L1_C_Clsall    = 0x0016 // C$Clsall
	L1_C_Clsgr     = 0x0015 // C$Clsgr
	L1_C_COMA      = 0x002C // C$COMA
	L1_C_CR        = 0x000D // C$CR
	L1_C_DEL       = 0x0018 // C$DEL
	L1_C_DELETE    = 0x0010 // C$DELETE
	L1_C_DWN       = 0x001F // C$DWN
	L1_C_EL        = 0x0005 // C$EL
	L1_C_EOF       = 0x001B // C$EOF
	L1_C_FORM      = 0x000C // C$FORM
	L1_C_HOME      = 0x000B // C$HOME
	L1_C_INSERT    = 0x0011 // C$INSERT
	L1_C_INTR      = 0x0003 // C$INTR
	L1_C_LF        = 0x000A // C$LF
	L1_C_LFT       = 0x001D // C$LFT
	L1_C_NULL      = 0x0000 // C$NULL
	L1_C_PAUS      = 0x0017 // C$PAUS
	L1_C_PERD      = 0x002E // C$PERD
	L1_C_PLINE     = 0x0013 // C$PLINE
	L1_C_QUIT      = 0x0005 // C$QUIT
	L1_C_RARR      = 0x0009 // C$RARR
	L1_C_RGT       = 0x001C // C$RGT
	L1_C_RPET      = 0x0001 // C$RPET
	L1_C_RPRT      = 0x0004 // C$RPRT
	L1_C_SHRARR    = 0x0019 // C$SHRARR
	L1_C_SI        = 0x000F // C$SI
	L1_C_SO        = 0x000E // C$SO
	L1_C_SPAC      = 0x0020 // C$SPAC
	L1_C_UP        = 0x001E // C$UP
	L1_C_XOFF      = 0x0013 // C$XOFF
	L1_C_XON       = 0x0011 // C$XON
	L1_COCO_D      = 0x0001 // COCO.D
	L1_D_GSTA      = 0x0009 // D$GSTA
	L1_D_INIT      = 0x0000 // D$INIT
	L1_D_PSTA      = 0x000C // D$PSTA
	L1_D_READ      = 0x0003 // D$READ
	L1_D_TERM      = 0x000F // D$TERM
	L1_D_WRIT      = 0x0006 // D$WRIT
	L1_D_AltIRQ    = 0x006B // D.AltIRQ
	L1_D_AProcQ    = 0x004D // D.AProcQ
	L1_D_Boot      = 0x0083 // D.Boot
	L1_D_BTHI      = 0x0068 // D.BTHI
	L1_D_BTLO      = 0x0066 // D.BTLO
	L1_D_CBStrt    = 0x0071 // D.CBStrt
	L1_D_Clock     = 0x0081 // D.Clock
	L1_D_Clock2    = 0x008A // D.Clock2
	L1_D_CLTb      = 0x0086 // D.CLTb
	L1_D_COCOXT    = 0x0009 // D.COCOXT
	L1_D_CRC       = 0x0089 // D.CRC
	L1_D_Day       = 0x0055 // D.Day
	L1_D_DbgMem    = 0x000A // D.DbgMem
	L1_D_DevTbl    = 0x0060 // D.DevTbl
	L1_D_DMAReq    = 0x006A // D.DMAReq
	L1_D_DskTmr    = 0x006F // D.DskTmr
	L1_D_DWSrvID   = 0x0010 // D.DWSrvID
	L1_D_DWStat    = 0x000E // D.DWStat
	L1_D_DWSubAddr = 0x000C // D.DWSubAddr
	L1_D_FIRQ      = 0x0030 // D.FIRQ
	L1_D_FMBM      = 0x0020 // D.FMBM
	L1_D_Hour      = 0x0056 // D.Hour
	L1_D_Init      = 0x002A // D.Init
	L1_D_IOMH      = 0x005E // D.IOMH
	L1_D_IOML      = 0x005C // D.IOML
	L1_D_IRQ       = 0x0032 // D.IRQ
	L1_D_KbdSta    = 0x006D // D.KbdSta
	L1_D_MDREG     = 0x0088 // D.MDREG
	L1_D_Min       = 0x0057 // D.Min
	L1_D_MLIM      = 0x0024 // D.MLIM
	L1_D_ModDir    = 0x0026 // D.ModDir
	L1_D_Month     = 0x0054 // D.Month
	L1_D_NMI       = 0x0036 // D.NMI
	L1_D_Poll      = 0x003A // D.Poll
	L1_D_PolTbl    = 0x0062 // D.PolTbl
	L1_D_PrcDBT    = 0x0049 // D.PrcDBT
	L1_D_Proc      = 0x004B // D.Proc
	L1_D_PthDBT    = 0x0064 // D.PthDBT
	L1_D_Sec       = 0x0058 // D.Sec
	L1_D_Slice     = 0x0048 // D.Slice
	L1_D_SProcQ    = 0x0051 // D.SProcQ
	L1_D_SvcIRQ    = 0x0038 // D.SvcIRQ
	L1_D_SWI       = 0x0034 // D.SWI
	L1_D_SWI2      = 0x002E // D.SWI2
	L1_D_SWI3      = 0x002C // D.SWI3
	L1_D_SWPage    = 0x0003 // D.SWPage
	L1_D_SysDis    = 0x0046 // D.SysDis
	L1_D_SysIRQ    = 0x003E // D.SysIRQ
	L1_D_SysSvc    = 0x0042 // D.SysSvc
	L1_D_Tick      = 0x0059 // D.Tick
	L1_D_Time      = 0x0053 // D.Time
	L1_D_TSec      = 0x005A // D.TSec
	L1_D_TSlice    = 0x005B // D.TSlice
	L1_D_URtoSs    = 0x0084 // D.URtoSs
	L1_D_UsrDis    = 0x0044 // D.UsrDis
	L1_D_UsrIRQ    = 0x003C // D.UsrIRQ
	L1_D_UsrSvc    = 0x0040 // D.UsrSvc
	L1_D_WDAddr    = 0x0000 // D.WDAddr
	L1_D_WDBtDr    = 0x0002 // D.WDBtDr
	L1_D_WProcQ    = 0x004F // D.WProcQ
	L1_D_XFIRQ     = 0x010F // D.XFIRQ
	L1_D_XIRQ      = 0x010C // D.XIRQ
	L1_D_XNMI      = 0x0109 // D.XNMI
	L1_D_XSWI      = 0x0106 // D.XSWI
	L1_D_XSWI2     = 0x0103 // D.XSWI2
	L1_D_XSWI3     = 0x0100 // D.XSWI3
	L1_D_Year      = 0x0053 // D.Year
	L1_DD_ATT      = 0x000D // DD.ATT
	L1_DD_BIT      = 0x0006 // DD.BIT
	L1_DD_BSZ      = 0x0018 // DD.BSZ
	L1_DD_BT       = 0x0015 // DD.BT
	L1_DD_DAT      = 0x001A // DD.DAT
	L1_DD_DIR      = 0x0008 // DD.DIR
	L1_DD_DSK      = 0x000E // DD.DSK
	L1_DD_FMT      = 0x0010 // DD.FMT
	L1_DD_MAP      = 0x0004 // DD.MAP
	L1_DD_NAM      = 0x001F // DD.NAM
	L1_DD_OPT      = 0x003F // DD.OPT
	L1_DD_OWN      = 0x000B // DD.OWN
	L1_DD_RES      = 0x0013 // DD.RES
	L1_DD_SIZ      = 0x0015 // DD.SIZ
	L1_DD_SPT      = 0x0011 // DD.SPT
	L1_DD_TKS      = 0x0003 // DD.TKS
	L1_DD_TOT      = 0x0000 // DD.TOT
	L1_DIR_        = 0x0080 // DIR.
	L1_DIR_FD      = 0x001D // DIR.FD
	L1_DIR_NM      = 0x0000 // DIR.NM
	L1_DIR_SZ      = 0x0020 // DIR.SZ
	L1_DNS_DTD     = 0x0002 // DNS.DTD
	L1_DNS_FM      = 0x0000 // DNS.FM
	L1_DNS_FM0     = 0x0000 // DNS.FM0
	L1_DNS_MFM     = 0x0001 // DNS.MFM
	L1_DNS_MFM0    = 0x0004 // DNS.MFM0
	L1_DNS_STD     = 0x0000 // DNS.STD
	L1_DT_CDFM     = 0x0005 // DT.CDFM
	L1_DT_NFM      = 0x0004 // DT.NFM
	L1_DT_Pipe     = 0x0002 // DT.Pipe
	L1_DT_RBF      = 0x0001 // DT.RBF
	L1_DT_RFM      = 0x0006 // DT.RFM
	L1_DT_SBF      = 0x0003 // DT.SBF
	L1_DT_SCF      = 0x0000 // DT.SCF
	L1_E_Alias     = 0x00C7 // E$Alias
	L1_E_ArrOvf    = 0x0049 // E$ArrOvf
	L1_E_BadBuf    = 0x00C2 // E$BadBuf
	L1_E_BMCRC     = 0x00E8 // E$BMCRC
	L1_E_BMHP      = 0x00EC // E$BMHP
	L1_E_BMID      = 0x00CD // E$BMID
	L1_E_BMode     = 0x00CB // E$BMode
	L1_E_BNam      = 0x00EB // E$BNam
	L1_E_BPAddr    = 0x00D2 // E$BPAddr
	L1_E_BPNam     = 0x00D7 // E$BPNam
	L1_E_BPNum     = 0x00C9 // E$BPNum
	L1_E_BPrcID    = 0x00E0 // E$BPrcID
	L1_E_BTyp      = 0x00F9 // E$BTyp
	L1_E_BufSiz    = 0x00BF // E$BufSiz
	L1_E_Bug       = 0x00BE // E$Bug
	L1_E_CEF       = 0x00DA // E$CEF
	L1_E_CRC       = 0x00F3 // E$CRC
	L1_E_DeadLk    = 0x00FE // E$DeadLk
	L1_E_DelSP     = 0x00DF // E$DelSP
	L1_E_DevBsy    = 0x00FA // E$DevBsy
	L1_E_DevOvf    = 0x00CC // E$DevOvf
	L1_E_DIDC      = 0x00FB // E$DIDC
	L1_E_DimLrg    = 0x0019 // E$DimLrg
	L1_E_DirFul    = 0x00CE // E$DirFul
	L1_E_DivZer    = 0x002D // E$DivZer
	L1_E_Dn        = 0x00C6 // E$Dn
	L1_E_DNE       = 0x00EE // E$DNE
	L1_E_EndQou    = 0x0029 // E$EndQou
	L1_E_EOF       = 0x00D3 // E$EOF
	L1_E_ExcVrb    = 0x000B // E$ExcVrb
	L1_E_FltOvf    = 0x0032 // E$FltOvf
	L1_E_FNA       = 0x00D6 // E$FNA
	L1_E_Full      = 0x00F8 // E$Full
	L1_E_HangUp    = 0x00DC // E$HangUp
	L1_E_IBA       = 0x00DB // E$IBA
	L1_E_IChRef    = 0x000E // E$IChRef
	L1_E_ICoord    = 0x00BD // E$ICoord
	L1_E_ICOvf     = 0x000D // E$ICOvf
	L1_E_IForkP    = 0x00E6 // E$IForkP
	L1_E_IllA      = 0x0043 // E$IllA
	L1_E_IllArg    = 0x00BB // E$IllArg
	L1_E_IllCmd    = 0x00C0 // E$IllCmd
	L1_E_IllCnt    = 0x0044 // E$IllCnt
	L1_E_IllDec    = 0x0048 // E$IllDec
	L1_E_IllDim    = 0x0015 // E$IllDim
	L1_E_IllExp    = 0x0047 // E$IllExp
	L1_E_IllFOR    = 0x0046 // E$IllFOR
	L1_E_IllInp    = 0x003D // E$IllInp
	L1_E_IllIVr    = 0x004D // E$IllIVr
	L1_E_IllLit    = 0x0016 // E$IllLit
	L1_E_IllMod    = 0x000F // E$IllMod
	L1_E_IllNum    = 0x0010 // E$IllNum
	L1_E_IllOpd    = 0x0012 // E$IllOpd
	L1_E_IllOpr    = 0x0013 // E$IllOpr
	L1_E_IllPNm    = 0x0040 // E$IllPNm
	L1_E_IllPrf    = 0x0011 // E$IllPrf
	L1_E_IllRet    = 0x0017 // E$IllRet
	L1_E_IllRFN    = 0x0014 // E$IllRFN
	L1_E_IllSfx    = 0x0018 // E$IllSfx
	L1_E_IllStC    = 0x000C // E$IllStC
	L1_E_IOConv    = 0x003C // E$IOConv
	L1_E_IOFRpt    = 0x003E // E$IOFRpt
	L1_E_IOFSyn    = 0x003F // E$IOFSyn
	L1_E_IOMism    = 0x003A // E$IOMism
	L1_E_IONum     = 0x003B // E$IONum
	L1_E_IPrcID    = 0x00E0 // E$IPrcID
	L1_E_ISWI      = 0x00E3 // E$ISWI
	L1_E_IWDef     = 0x00C3 // E$IWDef
	L1_E_IWTyp     = 0x00B7 // E$IWTyp
	L1_E_KwnMod    = 0x00E7 // E$KwnMod
	L1_E_LinLrg    = 0x001A // E$LinLrg
	L1_E_LnComp    = 0x0033 // E$LnComp
	L1_E_Lock      = 0x00FC // E$Lock
	L1_E_MemFul    = 0x00CF // E$MemFul
	L1_E_MFull     = 0x0020 // E$MFull
	L1_E_MltLin    = 0x004B // E$MltLin
	L1_E_MltVar    = 0x004C // E$MltVar
	L1_E_MNF       = 0x00DD // E$MNF
	L1_E_ModBsy    = 0x00D1 // E$ModBsy
	L1_E_MulPrc    = 0x002C // E$MulPrc
	L1_E_NEMod     = 0x00EA // E$NEMod
	L1_E_NES       = 0x00D5 // E$NES
	L1_E_NFont     = 0x00B9 // E$NFont
	L1_E_NoAssg    = 0x001B // E$NoAssg
	L1_E_NoChld    = 0x00E2 // E$NoChld
	L1_E_NoComa    = 0x001D // E$NoComa
	L1_E_NoData    = 0x004F // E$NoData
	L1_E_NoDim     = 0x001E // E$NoDim
	L1_E_NoDO      = 0x001F // E$NoDO
	L1_E_NoGoto    = 0x0021 // E$NoGoto
	L1_E_NoLPar    = 0x0022 // E$NoLPar
	L1_E_NoLRef    = 0x0023 // E$NoLRef
	L1_E_NonRcO    = 0x0042 // E$NonRcO
	L1_E_NoOprd    = 0x0024 // E$NoOprd
	L1_E_NoPath    = 0x001C // E$NoPath
	L1_E_NoRAM     = 0x00ED // E$NoRAM
	L1_E_NoRout    = 0x0030 // E$NoRout
	L1_E_NoRPar    = 0x0025 // E$NoRPar
	L1_E_NoTask    = 0x00EF // E$NoTask
	L1_E_NoTHEN    = 0x0026 // E$NoTHEN
	L1_E_NoTO      = 0x0027 // E$NoTO
	L1_E_NotRdy    = 0x00F6 // E$NotRdy
	L1_E_NoVRef    = 0x0028 // E$NoVRef
	L1_E_ParmEr    = 0x0038 // E$ParmEr
	L1_E_PNNF      = 0x00D8 // E$PNNF
	L1_E_Poll      = 0x00CA // E$Poll
	L1_E_PrcAbt    = 0x00E4 // E$PrcAbt
	L1_E_PrcFul    = 0x00E5 // E$PrcFul
	L1_E_PthFul    = 0x00C8 // E$PthFul
	L1_E_Read      = 0x00F4 // E$Read
	L1_E_Sect      = 0x00F1 // E$Sect
	L1_E_Seek      = 0x00F7 // E$Seek
	L1_E_SeekRg    = 0x004E // E$SeekRg
	L1_E_Share     = 0x00FD // E$Share
	L1_E_SLF       = 0x00D9 // E$SLF
	L1_E_StkOvf    = 0x00BA // E$StkOvf
	L1_E_StrOvf    = 0x002F // E$StrOvf
	L1_E_SubLrg    = 0x002A // E$SubLrg
	L1_E_SubOvf    = 0x0035 // E$SubOvf
	L1_E_SubRng    = 0x0037 // E$SubRng
	L1_E_SubUnd    = 0x0036 // E$SubUnd
	L1_E_SysOvf    = 0x0039 // E$SysOvf
	L1_E_TblFul    = 0x00C1 // E$TblFul
	L1_E_TypMis    = 0x002E // E$TypMis
	L1_E_UndLin    = 0x004A // E$UndLin
	L1_E_UndVar    = 0x0031 // E$UndVar
	L1_E_Unit      = 0x00F0 // E$Unit
	L1_E_UnkPrc    = 0x002B // E$UnkPrc
	L1_E_UnkSvc    = 0x00D0 // E$UnkSvc
	L1_E_UnkSym    = 0x000A // E$UnkSym
	L1_E_UnmCnt    = 0x0045 // E$UnmCnt
	L1_E_Up        = 0x00C5 // E$Up
	L1_E_USigP     = 0x00E9 // E$USigP
	L1_E_ValRng    = 0x0034 // E$ValRng
	L1_E_WADef     = 0x00B8 // E$WADef
	L1_E_WP        = 0x00F2 // E$WP
	L1_E_Write     = 0x00F5 // E$Write
	L1_E_WrSub     = 0x0041 // E$WrSub
	L1_E_WUndef    = 0x00C4 // E$WUndef
	L1_EXEC_       = 0x0004 // EXEC.
	L1_F_All64     = 0x0030 // F$All64
	L1_F_AllBit    = 0x0013 // F$AllBit
	L1_F_AProc     = 0x002C // F$AProc
	L1_F_Chain     = 0x0005 // F$Chain
	L1_F_CmpNam    = 0x0011 // F$CmpNam
	L1_F_CRC       = 0x0017 // F$CRC
	L1_F_Debug     = 0x0023 // F$Debug
	L1_F_DelBit    = 0x0014 // F$DelBit
	L1_F_Exit      = 0x0006 // F$Exit
	L1_F_Find64    = 0x002F // F$Find64
	L1_F_Fork      = 0x0003 // F$Fork
	L1_F_Icpt      = 0x0009 // F$Icpt
	L1_F_ID        = 0x000C // F$ID
	L1_F_IODel     = 0x0033 // F$IODel
	L1_F_IOQu      = 0x002B // F$IOQu
	L1_F_IRQ       = 0x002A // F$IRQ
	L1_F_Link      = 0x0000 // F$Link
	L1_F_Load      = 0x0001 // F$Load
	L1_F_Mem       = 0x0007 // F$Mem
	L1_F_NProc     = 0x002D // F$NProc
	L1_F_PErr      = 0x000F // F$PErr
	L1_F_PrsNam    = 0x0010 // F$PrsNam
	L1_F_Ret64     = 0x0031 // F$Ret64
	L1_F_SchBit    = 0x0012 // F$SchBit
	L1_F_Send      = 0x0008 // F$Send
	L1_F_Sleep     = 0x000A // F$Sleep
	L1_F_SPrior    = 0x000D // F$SPrior
	L1_F_SRqMem    = 0x0028 // F$SRqMem
	L1_F_SRtMem    = 0x0029 // F$SRtMem
	L1_F_SSpd      = 0x000B // F$SSpd
	L1_F_SSvc      = 0x0032 // F$SSvc
	L1_F_SSWI      = 0x000E // F$SSWI
	L1_F_STime     = 0x0016 // F$STime
	L1_F_Time      = 0x0015 // F$Time
	L1_F_UnLink    = 0x0002 // F$UnLink
	L1_F_VIRQ      = 0x0027 // F$VIRQ
	L1_F_VModul    = 0x002E // F$VModul
	L1_F_Wait      = 0x0004 // F$Wait
	L1_FD_ATT      = 0x0000 // FD.ATT
	L1_FD_Creat    = 0x000D // FD.Creat
	L1_FD_DAT      = 0x0003 // FD.DAT
	L1_FD_LNK      = 0x0008 // FD.LNK
	L1_FD_LS1      = 0x00FB // FD.LS1
	L1_FD_LS2      = 0x00FA // FD.LS2
	L1_FD_OWN      = 0x0001 // FD.OWN
	L1_FD_SEG      = 0x0010 // FD.SEG
	L1_FD_SIZ      = 0x0009 // FD.SIZ
	L1_FDSL_A      = 0x0000 // FDSL.A
	L1_FDSL_B      = 0x0003 // FDSL.B
	L1_FDSL_S      = 0x0005 // FDSL.S
	L1_FMT_DNS     = 0x0002 // FMT.DNS
	L1_FMT_SIDE    = 0x0001 // FMT.SIDE
	L1_FMT_T0DN    = 0x0020 // FMT.T0DN
	L1_FMT_TDNS    = 0x0004 // FMT.TDNS
	L1_HW_Page     = 0x00FF // HW.Page
	L1_I_Attach    = 0x0080 // I$Attach
	L1_I_ChgDir    = 0x0086 // I$ChgDir
	L1_I_Close     = 0x008F // I$Close
	L1_I_Create    = 0x0083 // I$Create
	L1_I_Delete    = 0x0087 // I$Delete
	L1_I_DeletX    = 0x0090 // I$DeletX
	L1_I_Detach    = 0x0081 // I$Detach
	L1_I_Dup       = 0x0082 // I$Dup
	L1_I_GetStt    = 0x008D // I$GetStt
	L1_I_MakDir    = 0x0085 // I$MakDir
	L1_I_Open      = 0x0084 // I$Open
	L1_I_Read      = 0x0089 // I$Read
	L1_I_ReadLn    = 0x008B // I$ReadLn
	L1_I_Seek      = 0x0088 // I$Seek
	L1_I_SetStt    = 0x008E // I$SetStt
	L1_I_Write     = 0x008A // I$Write
	L1_I_WritLn    = 0x008C // I$WritLn
	L1_ISIZ_       = 0x0020 // ISIZ.
	L1_IT_ALF      = 0x0017 // IT.ALF
	L1_IT_BAU      = 0x0027 // IT.BAU
	L1_IT_BSE      = 0x0024 // IT.BSE
	L1_IT_BSO      = 0x0014 // IT.BSO
	L1_IT_BSP      = 0x001B // IT.BSP
	L1_IT_COL      = 0x002C // IT.COL
	L1_IT_CYL      = 0x0017 // IT.CYL
	L1_IT_D2P      = 0x0028 // IT.D2P
	L1_IT_DEL      = 0x001C // IT.DEL
	L1_IT_DLO      = 0x0015 // IT.DLO
	L1_IT_DNS      = 0x0016 // IT.DNS
	L1_IT_DRV      = 0x0013 // IT.DRV
	L1_IT_DTP      = 0x0012 // IT.DTP
	L1_IT_DUP      = 0x0020 // IT.DUP
	L1_IT_DVC      = 0x0012 // IT.DVC
	L1_IT_EKO      = 0x0016 // IT.EKO
	L1_IT_EOF      = 0x001E // IT.EOF
	L1_IT_EOR      = 0x001D // IT.EOR
	L1_IT_Exten    = 0x0022 // IT.Exten
	L1_IT_ILV      = 0x001F // IT.ILV
	L1_IT_INT      = 0x0022 // IT.INT
	L1_IT_LLDRV    = 0x0028 // IT.LLDRV
	L1_IT_MPI      = 0x002A // IT.MPI
	L1_IT_NUL      = 0x0018 // IT.NUL
	L1_IT_OFS      = 0x0026 // IT.OFS
	L1_IT_OVF      = 0x0025 // IT.OVF
	L1_IT_PAG      = 0x001A // IT.PAG
	L1_IT_PAR      = 0x0026 // IT.PAR
	L1_IT_PAU      = 0x0019 // IT.PAU
	L1_IT_PSC      = 0x0021 // IT.PSC
	L1_IT_QUT      = 0x0023 // IT.QUT
	L1_IT_ROW      = 0x002D // IT.ROW
	L1_IT_RPR      = 0x001F // IT.RPR
	L1_IT_RWC      = 0x0028 // IT.RWC
	L1_IT_SAS      = 0x0020 // IT.SAS
	L1_IT_SCT      = 0x001B // IT.SCT
	L1_IT_SID      = 0x0019 // IT.SID
	L1_IT_SOFF1    = 0x0025 // IT.SOFF1
	L1_IT_SOFF2    = 0x0026 // IT.SOFF2
	L1_IT_SOFF3    = 0x0027 // IT.SOFF3
	L1_IT_SToff    = 0x0024 // IT.SToff
	L1_IT_STP      = 0x0014 // IT.STP
	L1_IT_T0S      = 0x001D // IT.T0S
	L1_IT_TFM      = 0x0021 // IT.TFM
	L1_IT_TYP      = 0x0015 // IT.TYP
	L1_IT_UPC      = 0x0013 // IT.UPC
	L1_IT_VFY      = 0x001A // IT.VFY
	L1_IT_WPC      = 0x0025 // IT.WPC
	L1_IT_XOFF     = 0x002B // IT.XOFF
	L1_IT_XON      = 0x002A // IT.XON
	L1_IT_XTYP     = 0x002E // IT.XTYP
	L1_M_DTyp      = 0x0012 // M$DTyp
	L1_M_Exec      = 0x0009 // M$Exec
	L1_M_FMgr      = 0x0009 // M$FMgr
	L1_M_ID        = 0x0000 // M$ID
	L1_M_ID1       = 0x0087 // M$ID1
	L1_M_ID12      = 0x87CD // M$ID12
	L1_M_ID2       = 0x00CD // M$ID2
	L1_M_IDSize    = 0x0009 // M$IDSize
	L1_M_Mem       = 0x000B // M$Mem
	L1_M_Mode      = 0x000D // M$Mode
	L1_M_Name      = 0x0004 // M$Name
	L1_M_Opt       = 0x0011 // M$Opt
	L1_M_Parity    = 0x0008 // M$Parity
	L1_M_PDev      = 0x000B // M$PDev
	L1_M_Port      = 0x000E // M$Port
	L1_M_Revs      = 0x0007 // M$Revs
	L1_M_Size      = 0x0002 // M$Size
	L1_M_Type      = 0x0006 // M$Type
	L1_MD_ESize    = 0x0004 // MD$ESize
	L1_MD_Link     = 0x0002 // MD$Link
	L1_MD_MPtr     = 0x0000 // MD$MPtr
	L1_MPI_Slct    = 0xFF7F // MPI.Slct
	L1_MPI_Slot    = 0x0003 // MPI.Slot
	L1_P_ADDR      = 0x0007 // P$ADDR
	L1_P_Age       = 0x000C // P$Age
	L1_P_CHAP      = 0x0006 // P$CHAP
	L1_P_CID       = 0x0003 // P$CID
	L1_P_DIO       = 0x001A // P$DIO
	L1_P_ID        = 0x0000 // P$ID
	L1_P_IOQN      = 0x0011 // P$IOQN
	L1_P_IOQP      = 0x0010 // P$IOQP
	L1_P_NIO       = 0x003B // P$NIO
	L1_P_PagCnt    = 0x0008 // P$PagCnt
	L1_P_PATH      = 0x0026 // P$PATH
	L1_P_PID       = 0x0001 // P$PID
	L1_P_PModul    = 0x0012 // P$PModul
	L1_P_Prior     = 0x000B // P$Prior
	L1_P_Queue     = 0x000E // P$Queue
	L1_P_SID       = 0x0002 // P$SID
	L1_P_SigDat    = 0x0039 // P$SigDat
	L1_P_Signal    = 0x0036 // P$Signal
	L1_P_SigVec    = 0x0037 // P$SigVec
	L1_P_Size      = 0x0040 // P$Size
	L1_P_SP        = 0x0004 // P$SP
	L1_P_State     = 0x000D // P$State
	L1_P_SWI       = 0x0014 // P$SWI
	L1_P_SWI2      = 0x0016 // P$SWI2
	L1_P_SWI3      = 0x0018 // P$SWI3
	L1_P_User      = 0x0009 // P$User
	L1_PD_ALF      = 0x0025 // PD.ALF
	L1_PD_ATT      = 0x0033 // PD.ATT
	L1_PD_BAU      = 0x0035 // PD.BAU
	L1_PD_BSE      = 0x0032 // PD.BSE
	L1_PD_BSO      = 0x0022 // PD.BSO
	L1_PD_BSP      = 0x0029 // PD.BSP
	L1_PD_BUF      = 0x0008 // PD.BUF
	L1_PD_CNT      = 0x0002 // PD.CNT
	L1_PD_CP       = 0x000B // PD.CP
	L1_PD_CPR      = 0x0005 // PD.CPR
	L1_PD_CYL      = 0x0025 // PD.CYL
	L1_PD_D2P      = 0x0036 // PD.D2P
	L1_PD_DCP      = 0x003A // PD.DCP
	L1_PD_DEL      = 0x002A // PD.DEL
	L1_PD_DEV      = 0x0003 // PD.DEV
	L1_PD_DFD      = 0x0037 // PD.DFD
	L1_PD_DLO      = 0x0023 // PD.DLO
	L1_PD_DNS      = 0x0024 // PD.DNS
	L1_PD_DRV      = 0x0021 // PD.DRV
	L1_PD_DSK      = 0x001C // PD.DSK
	L1_PD_DTB      = 0x001E // PD.DTB
	L1_PD_DTP      = 0x0020 // PD.DTP
	L1_PD_DUP      = 0x002E // PD.DUP
	L1_PD_DV2      = 0x000A // PD.DV2
	L1_PD_DVT      = 0x003E // PD.DVT
	L1_PD_EKO      = 0x0024 // PD.EKO
	L1_PD_EOF      = 0x002C // PD.EOF
	L1_PD_EOR      = 0x002B // PD.EOR
	L1_PD_ERR      = 0x003A // PD.ERR
	L1_PD_Exten    = 0x0030 // PD.Exten
	L1_PD_FD       = 0x0034 // PD.FD
	L1_PD_FST      = 0x000A // PD.FST
	L1_PD_ILV      = 0x002D // PD.ILV
	L1_PD_INT      = 0x0030 // PD.INT
	L1_PD_MAX      = 0x000D // PD.MAX
	L1_PD_MIN      = 0x000F // PD.MIN
	L1_PD_MOD      = 0x0001 // PD.MOD
	L1_PD_NUL      = 0x0026 // PD.NUL
	L1_PD_OPT      = 0x0020 // PD.OPT
	L1_PD_OVF      = 0x0033 // PD.OVF
	L1_PD_PAG      = 0x0028 // PD.PAG
	L1_PD_PAR      = 0x0034 // PD.PAR
	L1_PD_PAU      = 0x0027 // PD.PAU
	L1_PD_PD       = 0x0000 // PD.PD
	L1_PD_PLP      = 0x003D // PD.PLP
	L1_PD_PSC      = 0x002F // PD.PSC
	L1_PD_PST      = 0x003F // PD.PST
	L1_PD_QUT      = 0x0031 // PD.QUT
	L1_PD_RAW      = 0x000C // PD.RAW
	L1_PD_RGS      = 0x0006 // PD.RGS
	L1_PD_RPR      = 0x002D // PD.RPR
	L1_PD_SAS      = 0x002E // PD.SAS
	L1_PD_SBL      = 0x0013 // PD.SBL
	L1_PD_SBP      = 0x0016 // PD.SBP
	L1_PD_SCT      = 0x0029 // PD.SCT
	L1_PD_SID      = 0x0027 // PD.SID
	L1_PD_SIZ      = 0x000F // PD.SIZ
	L1_PD_SMF      = 0x000A // PD.SMF
	L1_PD_SSZ      = 0x0019 // PD.SSZ
	L1_PD_STM      = 0x0012 // PD.STM
	L1_PD_SToff    = 0x0032 // PD.SToff
	L1_PD_STP      = 0x0022 // PD.STP
	L1_PD_STS      = 0x0010 // PD.STS
	L1_PD_T0S      = 0x002B // PD.T0S
	L1_PD_TBL      = 0x003B // PD.TBL
	L1_PD_TFM      = 0x002F // PD.TFM
	L1_PD_TYP      = 0x0023 // PD.TYP
	L1_PD_UPC      = 0x0021 // PD.UPC
	L1_PD_VFY      = 0x0028 // PD.VFY
	L1_PD_XOFF     = 0x0039 // PD.XOFF
	L1_PD_XON      = 0x0038 // PD.XON
	L1_PEXEC_      = 0x0020 // PEXEC.
	L1_PREAD_      = 0x0008 // PREAD.
	L1_PST_DCD     = 0x0001 // PST.DCD
	L1_PWRIT_      = 0x0010 // PWRIT.
	L1_Q_FLIP      = 0x0002 // Q$FLIP
	L1_Q_MASK      = 0x0003 // Q$MASK
	L1_Q_POLL      = 0x0000 // Q$POLL
	L1_Q_PRTY      = 0x0008 // Q$PRTY
	L1_Q_SERV      = 0x0004 // Q$SERV
	L1_Q_STAT      = 0x0006 // Q$STAT
	L1_R_A         = 0x0001 // R$A
	L1_R_B         = 0x0002 // R$B
	L1_R_CC        = 0x0000 // R$CC
	L1_R_D         = 0x0001 // R$D
	L1_R_DP        = 0x0003 // R$DP
	L1_R_PC        = 0x000A // R$PC
	L1_R_Size      = 0x000C // R$Size
	L1_R_U         = 0x0008 // R$U
	L1_R_X         = 0x0004 // R$X
	L1_R_Y         = 0x0006 // R$Y
	L1_RBF_D       = 0x0001 // RBF.D
	L1_READ_       = 0x0001 // READ.
	L1_S_Abort     = 0x0002 // S$Abort
	L1_S_Alarm     = 0x0005 // S$Alarm
	L1_S_HUP       = 0x0004 // S$HUP
	L1_S_Intrpt    = 0x0003 // S$Intrpt
	L1_S_Kill      = 0x0000 // S$Kill
	L1_S_Wake      = 0x0001 // S$Wake
	L1_S_Window    = 0x0004 // S$Window
	L1_SCF_D       = 0x0001 // SCF.D
	L1_SHARE_      = 0x0040 // SHARE.
	L1_SS_AAGBf    = 0x0080 // SS.AAGBf
	L1_SS_AlfaS    = 0x001C // SS.AlfaS
	L1_SS_AnPal    = 0x009A // SS.AnPal
	L1_SS_AScrn    = 0x008B // SS.AScrn
	L1_SS_Attr     = 0x001C // SS.Attr
	L1_SS_BlkRd    = 0x0014 // SS.BlkRd
	L1_SS_BlkWr    = 0x0015 // SS.BlkWr
	L1_SS_Break    = 0x001D // SS.Break
	L1_SS_CDRel    = 0x009B // SS.CDRel
	L1_SS_CDSig    = 0x009A // SS.CDSig
	L1_SS_CDSta    = 0x0099 // SS.CDSta
	L1_SS_Close    = 0x002A // SS.Close
	L1_SS_ComSt    = 0x0028 // SS.ComSt
	L1_SS_Cursr    = 0x0025 // SS.Cursr
	L1_SS_DCmd     = 0x000D // SS.DCmd
	L1_SS_DevNm    = 0x000E // SS.DevNm
	L1_SS_DfPal    = 0x0097 // SS.DfPal
	L1_SS_DirEnt   = 0x0020 // SS.DirEnt
	L1_SS_DScrn    = 0x008C // SS.DScrn
	L1_SS_DSize    = 0x0026 // SS.DSize
	L1_SS_DStat    = 0x0012 // SS.DStat
	L1_SS_ECC      = 0x00B0 // SS.ECC
	L1_SS_ELog     = 0x0019 // SS.ELog
	L1_SS_EOF      = 0x0006 // SS.EOF
	L1_SS_FBRgs    = 0x0096 // SS.FBRgs
	L1_SS_FD       = 0x000F // SS.FD
	L1_SS_FDInf    = 0x0020 // SS.FDInf
	L1_SS_Feed     = 0x0009 // SS.Feed
	L1_SS_Fill     = 0x00A0 // SS.Fill
	L1_SS_FndBf    = 0x009B // SS.FndBf
	L1_SS_Frz      = 0x000A // SS.Frz
	L1_SS_FScrn    = 0x008D // SS.FScrn
	L1_SS_FSig     = 0x002C // SS.FSig
	L1_SS_GIP      = 0x0094 // SS.GIP
	L1_SS_GIP2     = 0x0099 // SS.GIP2
	L1_SS_Hist     = 0x00A1 // SS.Hist
	L1_SS_HngUp    = 0x002B // SS.HngUp
	L1_SS_Joy      = 0x0013 // SS.Joy
	L1_SS_KySns    = 0x0027 // SS.KySns
	L1_SS_Link     = 0x0007 // SS.Link
	L1_SS_Lock     = 0x0011 // SS.Lock
	L1_SS_MnSel    = 0x0087 // SS.MnSel
	L1_SS_Montr    = 0x0092 // SS.Montr
	L1_SS_Mount    = 0x0082 // SS.Mount
	L1_SS_Mouse    = 0x0089 // SS.Mouse
	L1_SS_MpGPB    = 0x0084 // SS.MpGPB
	L1_SS_MsSig    = 0x008A // SS.MsSig
	L1_SS_Open     = 0x0029 // SS.Open
	L1_SS_Opt      = 0x0000 // SS.Opt
	L1_SS_Palet    = 0x0091 // SS.Palet
	L1_SS_Pos      = 0x0005 // SS.Pos
	L1_SS_PScrn    = 0x008E // SS.PScrn
	L1_SS_RdNet    = 0x0083 // SS.RdNet
	L1_SS_Ready    = 0x0001 // SS.Ready
	L1_SS_Relea    = 0x001B // SS.Relea
	L1_SS_Reset    = 0x0003 // SS.Reset
	L1_SS_Reten    = 0x0016 // SS.Reten
	L1_SS_RFM      = 0x0018 // SS.RFM
	L1_SS_RsBit    = 0x001E // SS.RsBit
	L1_SS_SBar     = 0x0088 // SS.SBar
	L1_SS_ScInf    = 0x008F // SS.ScInf
	L1_SS_ScSiz    = 0x0026 // SS.ScSiz
	L1_SS_ScTyp    = 0x0093 // SS.ScTyp
	L1_SS_SetMF    = 0x0024 // SS.SetMF
	L1_SS_Size     = 0x0002 // SS.Size
	L1_SS_SLGBf    = 0x0081 // SS.SLGBf
	L1_SS_Slots    = 0x0085 // SS.Slots
	L1_SS_SPT      = 0x000B // SS.SPT
	L1_SS_SQD      = 0x000C // SS.SQD
	L1_SS_SSig     = 0x001A // SS.SSig
	L1_SS_Ticks    = 0x0010 // SS.Ticks
	L1_SS_Tone     = 0x0098 // SS.Tone
	L1_SS_ULink    = 0x0008 // SS.ULink
	L1_SS_UMBar    = 0x0095 // SS.UMBar
	L1_SS_VarSect  = 0x0012 // SS.VarSect
	L1_SS_WFM      = 0x0017 // SS.WFM
	L1_SS_WnSet    = 0x0086 // SS.WnSet
	L1_SS_WTrk     = 0x0004 // SS.WTrk
	L1_STP_12ms    = 0x0002 // STP.12ms
	L1_STP_20ms    = 0x0001 // STP.20ms
	L1_STP_30ms    = 0x0000 // STP.30ms
	L1_STP_6ms     = 0x0003 // STP.6ms
	L1_TYP_256     = 0x0000 // TYP.256
	L1_TYP_3       = 0x0001 // TYP.3
	L1_TYP_5       = 0x0000 // TYP.5
	L1_TYP_512     = 0x0004 // TYP.512
	L1_TYP_CCF     = 0x0020 // TYP.CCF
	L1_TYP_FLP     = 0x0000 // TYP.FLP
	L1_TYP_HARD    = 0x0080 // TYP.HARD
	L1_TYP_NCCF    = 0x0000 // TYP.NCCF
	L1_TYP_NSF     = 0x0040 // TYP.NSF
	L1_TYP_SBO     = 0x0002 // TYP.SBO
	L1_TYP_SOF     = 0x0000 // TYP.SOF
	L1_TYPH_1024   = 0x0002 // TYPH.1024
	L1_TYPH_2048   = 0x0003 // TYPH.2048
	L1_TYPH_256    = 0x0000 // TYPH.256
	L1_TYPH_512    = 0x0001 // TYPH.512
	L1_TYPH_DRSV   = 0x000C // TYPH.DRSV
	L1_TYPH_DSQ    = 0x0010 // TYPH.DSQ
	L1_TYPH_SSM    = 0x0003 // TYPH.SSM
	L1_UPDAT_      = 0x0003 // UPDAT.
	L1_V_DESC      = 0x0004 // V$DESC
	L1_V_DRIV      = 0x0000 // V$DRIV
	L1_V_FMGR      = 0x0006 // V$FMGR
	L1_V_STAT      = 0x0002 // V$STAT
	L1_V_USRS      = 0x0008 // V$USRS
	L1_V_BMapSz    = 0x001C // V.BMapSz
	L1_V_BMB       = 0x0017 // V.BMB
	L1_V_BUSY      = 0x0004 // V.BUSY
	L1_V_DEV2      = 0x0009 // V.DEV2
	L1_V_DiskID    = 0x001A // V.DiskID
	L1_V_ERR       = 0x000E // V.ERR
	L1_V_FileHd    = 0x0018 // V.FileHd
	L1_V_INTR      = 0x000B // V.INTR
	L1_V_KANJI     = 0x0011 // V.KANJI
	L1_V_KBUF      = 0x0012 // V.KBUF
	L1_V_LINE      = 0x0007 // V.LINE
	L1_V_LPRC      = 0x0003 // V.LPRC
	L1_V_MapSct    = 0x001D // V.MapSct
	L1_V_MODADR    = 0x0014 // V.MODADR
	L1_V_NDRV      = 0x0006 // V.NDRV
	L1_V_PAGE      = 0x0000 // V.PAGE
	L1_V_PAUS      = 0x0008 // V.PAUS
	L1_V_PCHR      = 0x000D // V.PCHR
	L1_V_PDLHd     = 0x0016 // V.PDLHd
	L1_V_PORT      = 0x0001 // V.PORT
	L1_V_QUIT      = 0x000C // V.QUIT
	L1_V_ResBit    = 0x001E // V.ResBit
	L1_V_RSV       = 0x0018 // V.RSV
	L1_V_SCF       = 0x001D // V.SCF
	L1_V_ScOfst    = 0x0020 // V.ScOfst
	L1_V_ScTkOf    = 0x001F // V.ScTkOf
	L1_V_TkOfst    = 0x0021 // V.TkOfst
	L1_V_TRAK      = 0x0015 // V.TRAK
	L1_V_TYPE      = 0x0006 // V.TYPE
	L1_V_USER      = 0x0006 // V.USER
	L1_V_WAKE      = 0x0005 // V.WAKE
	L1_V_XOFF      = 0x0010 // V.XOFF
	L1_V_XON       = 0x000F // V.XON
	L1_VD_OFS      = 0x0061 // VD.OFS
	L1_VD_STP      = 0x0060 // VD.STP
	L1_Vi_Cnt      = 0x0000 // Vi.Cnt
	L1_Vi_IFlag    = 0x0001 // Vi.IFlag
	L1_Vi_PkSz     = 0x0005 // Vi.PkSz
	L1_Vi_Rst      = 0x0002 // Vi.Rst
	L1_Vi_Stat     = 0x0004 // Vi.Stat
	L1_WRITE_      = 0x0002 // WRITE.
	L1_XX_Size     = 0x0006 // XX.Size
)

var L1_SysCallNames = map[byte]string{
	L1_F_AProc:  "F$AProc",
	L1_F_All64:  "F$All64",
	L1_F_AllBit: "F$AllBit",
	L1_F_CRC:    "F$CRC",
	L1_F_Chain:  "F$Chain",
	L1_F_CmpNam: "F$CmpNam",
	L1_F_Debug:  "F$Debug",
	L1_F_DelBit: "F$DelBit",
	L1_F_Exit:   "F$Exit",
	L1_F_Find64: "F$Find64",
	L1_F_Fork:   "F$Fork",
	L1_F_ID:     "F$ID",
	L1_F_IODel:  "F$IODel",
	L1_F_IOQu:   "F$IOQu",
	L1_F_IRQ:    "F$IRQ",
	L1_F_Icpt:   "F$Icpt",
	L1_F_Link:   "F$Link",
	L1_F_Load:   "F$Load",
	L1_F_Mem:    "F$Mem",
	L1_F_NProc:  "F$NProc",
	L1_F_PErr:   "F$PErr",
	L1_F_PrsNam: "F$PrsNam",
	L1_F_Ret64:  "F$Ret64",
	L1_F_SPrior: "F$SPrior",
	L1_F_SRqMem: "F$SRqMem",
	L1_F_SRtMem: "F$SRtMem",
	L1_F_SSWI:   "F$SSWI",
	L1_F_SSpd:   "F$SSpd",
	L1_F_SSvc:   "F$SSvc",
	L1_F_STime:  "F$STime",
	L1_F_SchBit: "F$SchBit",
	L1_F_Send:   "F$Send",
	L1_F_Sleep:  "F$Sleep",
	L1_F_Time:   "F$Time",
	L1_F_UnLink: "F$UnLink",
	L1_F_VIRQ:   "F$VIRQ",
	L1_F_VModul: "F$VModul",
	L1_F_Wait:   "F$Wait",
	L1_I_Attach: "I$Attach",
	L1_I_ChgDir: "I$ChgDir",
	L1_I_Close:  "I$Close",
	L1_I_Create: "I$Create",
	L1_I_DeletX: "I$DeletX",
	L1_I_Delete: "I$Delete",
	L1_I_Detach: "I$Detach",
	L1_I_Dup:    "I$Dup",
	L1_I_GetStt: "I$GetStt",
	L1_I_MakDir: "I$MakDir",
	L1_I_Open:   "I$Open",
	L1_I_Read:   "I$Read",
	L1_I_ReadLn: "I$ReadLn",
	L1_I_Seek:   "I$Seek",
	L1_I_SetStt: "I$SetStt",
	L1_I_WritLn: "I$WritLn",
	L1_I_Write:  "I$Write",
}

type Slot struct {
	off    uint
	symbol string
}

var L1_Slots_PD = []Slot{
	{0x0000, "PD"},
	{0x0001, "MOD"},
	{0x0002, "CNT"},
	{0x0003, "DEV"},
	{0x0005, "CPR"},
	{0x0006, "RGS"},
	{0x0008, "BUF"},
	{0x000a, "SMF"},
	{0x000b, "CP"},
	{0x000c, "RAW"},
	{0x000d, "MAX"},
	{0x000f, "SIZ"},
	{0x0010, "STS"},
	{0x0012, "STM"},
	{0x0013, "SBL"},
	{0x0016, "SBP"},
	{0x0019, "SSZ"},
	{0x001c, "DSK"},
	{0x001e, "DTB"},
	{0x0020, "OPT"},
	{0x0021, "UPC"},
	{0x0022, "STP"},
	{0x0023, "TYP"},
	{0x0024, "EKO"},
	{0x0025, "CYL"},
	{0x0026, "NUL"},
	{0x0027, "SID"},
	{0x0028, "VFY"},
	{0x0029, "SCT"},
	{0x002a, "DEL"},
	{0x002b, "T0S"},
	{0x002c, "EOF"},
	{0x002d, "RPR"},
	{0x002e, "SAS"},
	{0x002f, "TFM"},
	{0x0030, "INT"},
	{0x0031, "QUT"},
	{0x0032, "SToff"},
	{0x0033, "OVF"},
	{0x0034, "PAR"},
	{0x0035, "BAU"},
	{0x0036, "D2P"},
	{0x0037, "DFD"},
	{0x0038, "XON"},
	{0x0039, "XOFF"},
	{0x003a, "ERR"},
	{0x003b, "TBL"},
	{0x003d, "PLP"},
	{0x003e, "DVT"},
	{0x003f, "PST"},
}
var L1_Slots_D = []Slot{
	{0x0000, "WDAddr"},
	{0x0002, "WDBtDr"},
	{0x0003, "SWPage"},
	{0x0009, "COCOXT"},
	{0x000a, "DbgMem"},
	{0x000c, "DWSubAddr"},
	{0x000e, "DWStat"},
	{0x0010, "DWSrvID"},
	{0x0020, "FMBM"},
	{0x0024, "MLIM"},
	{0x0026, "ModDir"},
	{0x002a, "Init"},
	{0x002c, "SWI3"},
	{0x002e, "SWI2"},
	{0x0030, "FIRQ"},
	{0x0032, "IRQ"},
	{0x0034, "SWI"},
	{0x0036, "NMI"},
	{0x0038, "SvcIRQ"},
	{0x003a, "Poll"},
	{0x003c, "UsrIRQ"},
	{0x003e, "SysIRQ"},
	{0x0040, "UsrSvc"},
	{0x0042, "SysSvc"},
	{0x0044, "UsrDis"},
	{0x0046, "SysDis"},
	{0x0048, "Slice"},
	{0x0049, "PrcDBT"},
	{0x004b, "Proc"},
	{0x004d, "AProcQ"},
	{0x004f, "WProcQ"},
	{0x0051, "SProcQ"},
	{0x0053, "Year"},
	{0x0054, "Month"},
	{0x0055, "Day"},
	{0x0056, "Hour"},
	{0x0057, "Min"},
	{0x0058, "Sec"},
	{0x0059, "Tick"},
	{0x005a, "TSec"},
	{0x005b, "TSlice"},
	{0x005c, "IOML"},
	{0x005e, "IOMH"},
	{0x0060, "DevTbl"},
	{0x0062, "PolTbl"},
	{0x0064, "PthDBT"},
	{0x0066, "BTLO"},
	{0x0068, "BTHI"},
	{0x006a, "DMAReq"},
	{0x006b, "AltIRQ"},
	{0x006d, "KbdSta"},
	{0x006f, "DskTmr"},
	{0x0071, "CBStrt"},
	{0x0081, "Clock"},
	{0x0083, "Boot"},
	{0x0084, "URtoSs"},
	{0x0086, "CLTb"},
	{0x0088, "MDREG"},
	{0x0089, "CRC"},
	{0x008a, "Clock2"},
	{0x0100, "XSWI3"},
	{0x0103, "XSWI2"},
	{0x0106, "XSWI"},
	{0x0109, "XNMI"},
	{0x010c, "XIRQ"},
	{0x010f, "XFIRQ"},
}
var L1_Slots_P = []Slot{
	{0x0000, "ID"},
	{0x0001, "PID"},
	{0x0002, "SID"},
	{0x0003, "CID"},
	{0x0004, "SP"},
	{0x0006, "CHAP"},
	{0x0007, "ADDR"},
	{0x0008, "PagCnt"},
	{0x0009, "User"},
	{0x000b, "Prior"},
	{0x000c, "Age"},
	{0x000d, "State"},
	{0x000e, "Queue"},
	{0x0010, "IOQP"},
	{0x0011, "IOQN"},
	{0x0012, "PModul"},
	{0x0014, "SWI"},
	{0x0016, "SWI2"},
	{0x0018, "SWI3"},
	{0x001a, "DIO"},
	{0x0026, "PATH"},
	{0x0036, "Signal"},
	{0x0037, "SigVec"},
	{0x0039, "SigDat"},
	{0x003b, "NIO"},
	{0x0040, "Size"},
}
var L1_Os9Error = map[byte]string{
	L1_E_Alias:  "E$Alias",
	L1_E_ArrOvf: "E$ArrOvf",
	L1_E_BMCRC:  "E$BMCRC",
	L1_E_BMHP:   "E$BMHP",
	L1_E_BMID:   "E$BMID",
	L1_E_BMode:  "E$BMode",
	L1_E_BNam:   "E$BNam",
	L1_E_BPAddr: "E$BPAddr",
	L1_E_BPNam:  "E$BPNam",
	L1_E_BPNum:  "E$BPNum",
	L1_E_BPrcID: "E$BPrcID",
	L1_E_BTyp:   "E$BTyp",
	L1_E_BadBuf: "E$BadBuf",
	L1_E_BufSiz: "E$BufSiz",
	L1_E_Bug:    "E$Bug",
	L1_E_CEF:    "E$CEF",
	L1_E_CRC:    "E$CRC",
	L1_E_DIDC:   "E$DIDC",
	L1_E_DNE:    "E$DNE",
	L1_E_DeadLk: "E$DeadLk",
	L1_E_DelSP:  "E$DelSP",
	L1_E_DevBsy: "E$DevBsy",
	L1_E_DevOvf: "E$DevOvf",
	L1_E_DimLrg: "E$DimLrg",
	L1_E_DirFul: "E$DirFul",
	L1_E_DivZer: "E$DivZer",
	L1_E_Dn:     "E$Dn",
	L1_E_EOF:    "E$EOF",
	L1_E_EndQou: "E$EndQou",
	L1_E_ExcVrb: "E$ExcVrb",
	L1_E_FNA:    "E$FNA",
	L1_E_FltOvf: "E$FltOvf",
	L1_E_Full:   "E$Full",
	L1_E_HangUp: "E$HangUp",
	L1_E_IBA:    "E$IBA",
	L1_E_ICOvf:  "E$ICOvf",
	L1_E_IChRef: "E$IChRef",
	L1_E_ICoord: "E$ICoord",
	L1_E_IForkP: "E$IForkP",
	L1_E_IOConv: "E$IOConv",
	L1_E_IOFRpt: "E$IOFRpt",
	L1_E_IOFSyn: "E$IOFSyn",
	L1_E_IOMism: "E$IOMism",
	L1_E_IONum:  "E$IONum",
	L1_E_ISWI:   "E$ISWI",
	L1_E_IWDef:  "E$IWDef",
	L1_E_IWTyp:  "E$IWTyp",
	L1_E_IllA:   "E$IllA",
	L1_E_IllArg: "E$IllArg",
	L1_E_IllCmd: "E$IllCmd",
	L1_E_IllCnt: "E$IllCnt",
	L1_E_IllDec: "E$IllDec",
	L1_E_IllDim: "E$IllDim",
	L1_E_IllExp: "E$IllExp",
	L1_E_IllFOR: "E$IllFOR",
	L1_E_IllIVr: "E$IllIVr",
	L1_E_IllInp: "E$IllInp",
	L1_E_IllLit: "E$IllLit",
	L1_E_IllMod: "E$IllMod",
	L1_E_IllNum: "E$IllNum",
	L1_E_IllOpd: "E$IllOpd",
	L1_E_IllOpr: "E$IllOpr",
	L1_E_IllPNm: "E$IllPNm",
	L1_E_IllPrf: "E$IllPrf",
	L1_E_IllRFN: "E$IllRFN",
	L1_E_IllRet: "E$IllRet",
	L1_E_IllSfx: "E$IllSfx",
	L1_E_IllStC: "E$IllStC",
	L1_E_KwnMod: "E$KwnMod",
	L1_E_LinLrg: "E$LinLrg",
	L1_E_LnComp: "E$LnComp",
	L1_E_Lock:   "E$Lock",
	L1_E_MFull:  "E$MFull",
	L1_E_MNF:    "E$MNF",
	L1_E_MemFul: "E$MemFul",
	L1_E_MltLin: "E$MltLin",
	L1_E_MltVar: "E$MltVar",
	L1_E_ModBsy: "E$ModBsy",
	L1_E_MulPrc: "E$MulPrc",
	L1_E_NEMod:  "E$NEMod",
	L1_E_NES:    "E$NES",
	L1_E_NFont:  "E$NFont",
	L1_E_NoAssg: "E$NoAssg",
	L1_E_NoChld: "E$NoChld",
	L1_E_NoComa: "E$NoComa",
	L1_E_NoDO:   "E$NoDO",
	L1_E_NoData: "E$NoData",
	L1_E_NoDim:  "E$NoDim",
	L1_E_NoGoto: "E$NoGoto",
	L1_E_NoLPar: "E$NoLPar",
	L1_E_NoLRef: "E$NoLRef",
	L1_E_NoOprd: "E$NoOprd",
	L1_E_NoPath: "E$NoPath",
	L1_E_NoRAM:  "E$NoRAM",
	L1_E_NoRPar: "E$NoRPar",
	L1_E_NoRout: "E$NoRout",
	L1_E_NoTHEN: "E$NoTHEN",
	L1_E_NoTO:   "E$NoTO",
	L1_E_NoTask: "E$NoTask",
	L1_E_NoVRef: "E$NoVRef",
	L1_E_NonRcO: "E$NonRcO",
	L1_E_NotRdy: "E$NotRdy",
	L1_E_PNNF:   "E$PNNF",
	L1_E_ParmEr: "E$ParmEr",
	L1_E_Poll:   "E$Poll",
	L1_E_PrcAbt: "E$PrcAbt",
	L1_E_PrcFul: "E$PrcFul",
	L1_E_PthFul: "E$PthFul",
	L1_E_Read:   "E$Read",
	L1_E_SLF:    "E$SLF",
	L1_E_Sect:   "E$Sect",
	L1_E_Seek:   "E$Seek",
	L1_E_SeekRg: "E$SeekRg",
	L1_E_Share:  "E$Share",
	L1_E_StkOvf: "E$StkOvf",
	L1_E_StrOvf: "E$StrOvf",
	L1_E_SubLrg: "E$SubLrg",
	L1_E_SubOvf: "E$SubOvf",
	L1_E_SubRng: "E$SubRng",
	L1_E_SubUnd: "E$SubUnd",
	L1_E_SysOvf: "E$SysOvf",
	L1_E_TblFul: "E$TblFul",
	L1_E_TypMis: "E$TypMis",
	L1_E_USigP:  "E$USigP",
	L1_E_UndLin: "E$UndLin",
	L1_E_UndVar: "E$UndVar",
	L1_E_Unit:   "E$Unit",
	L1_E_UnkPrc: "E$UnkPrc",
	L1_E_UnkSvc: "E$UnkSvc",
	L1_E_UnkSym: "E$UnkSym",
	L1_E_UnmCnt: "E$UnmCnt",
	L1_E_Up:     "E$Up",
	L1_E_ValRng: "E$ValRng",
	L1_E_WADef:  "E$WADef",
	L1_E_WP:     "E$WP",
	L1_E_WUndef: "E$WUndef",
	L1_E_WrSub:  "E$WrSub",
	L1_E_Write:  "E$Write",
}
var L1_Os9ErrorName = map[byte]string{
	183: "Illegal window type",
	184: "Window already defined",
	185: "Font Not found",
	186: "Stack Overflow",
	187: "Illegal Argument",
	188: "unused",
	189: "Illegal Coordinates",
	190: "Internal Integrity check",
	191: "Buffer size is too small",
	192: "Illegal Command",
	193: "Screen or Window Table is Full",
	194: "Bad/Undefined buffer number",
	195: "Illegal window definition",
	196: "Window undefined",
	197: "unused",
	198: "unused",
	199: "unused",
	200: "Path Table Full",
	201: "Illegal Path Number",
	202: "Interrupt Polling Table Full",
	203: "Illegal Mode",
	204: "Device Table Full",
	205: "Illegal Module Header",
	206: "Module Directory Full",
	207: "Memory Full",
	208: "Illegal Service Request",
	209: "Module Busy",
	210: "Boundary Error",
	211: "End of File",
	212: "Returning non-allocated memory",
	213: "Non-existing Segment",
	214: "No Permission",
	215: "Bad Path Name",
	216: "Path Name Not Found",
	217: "Segment List Full",
	218: "File Already Exists",
	219: "Illegal Block Address",
	220: "Phone Hangup-Data Carrier Detect lost",
	221: "Module Not Found",
	223: "Suicide Attempt",
	224: "Illegal Process Number",
	226: "No Children",
	227: "Illegal SWI Code",
	228: "Process Aborted",
	229: "Process Table Full",
	230: "Illegal Parameter Area",
	231: "Known module",
	232: "Incorrect Module CRC",
	233: "Signal Error",
	234: "Non-existent Module",
	235: "Bad Name",
	236: "Bad Module Header",
	237: "RAM Full",
	238: "Unknown Process ID",
	239: "No task number available",
	240: "Unit Error",
	241: "Sector Error",
	242: "Write Protect",
	243: "CRC Error",
	244: "Read Error",
	245: "Write Error",
	246: "Not Ready",
	247: "Seek Error",
	248: "Media Full",
	249: "Wrong Type",
	250: "Device Busy",
	251: "Disk ID Change",
	252: "Record is locked-out",
	253: "Non-sharable file busy",
	254: "I/O Deadlock Error",
	1:   "Unconditional Abort",
	2:   "Keyboard Abort",
	3:   "Keyboard Interrupt",
	10:  "Unrecognized Symbol",
	11:  "Excessive Verbage",
	12:  "Illegal Statement Construction",
	13:  "I-code Overflow",
	14:  "Illegal Channel Reference",
	15:  "Illegal Mode (read/write/update)",
	16:  "Illegal Number",
	17:  "Illegal Prefix",
	18:  "Illegal Operand",
	19:  "Illegal Operator",
	20:  "Illegal Record Field Name",
	21:  "Illegal Dimension",
	22:  "Illegal Literal",
	23:  "Illegal Relational",
	24:  "Illegal Type Suffix",
	25:  "Too-large Dimension",
	26:  "Too-large Line Number",
	27:  "Missing Assignment Statement",
	28:  "Missing Path Number",
	29:  "Missing Comma",
	30:  "Missing Dimension",
	31:  "Missing DO Statement",
	32:  "Memory Full",
	33:  "Missing GOTO",
	34:  "Missing Left Parenthesis",
	35:  "Missing Line Reference",
	36:  "Missing Operand",
	37:  "Missing Right Parenthesis",
	38:  "Missing THEN statement",
	39:  "Missing TO",
	40:  "Missing Variable Reference",
	41:  "No Ending Quote",
	42:  "Too Many Subscripts",
	43:  "Unknown Procedure",
	44:  "Multiply-defined Procedure",
	45:  "Divide by Zero",
	46:  "Operand Type Mismatch",
	47:  "String Stack Overflow",
	48:  "Unimplemented Routine",
	49:  "Undefined Variable",
	50:  "Floating Overflow",
	51:  "Line with Compiler Error",
	52:  "Value out of Range for Destination",
	53:  "Subroutine Stack Overflow",
	54:  "Subroutine Stack Underflow",
	55:  "Subscript out of Range",
	56:  "Parameter Error",
	57:  "System Stack Overflow",
	58:  "I/O Type Mismatch",
	59:  "I/O Numeric Input Format Bad",
	60:  "I/O Conversion: Number out of Range",
	61:  "Illegal Input Format",
	62:  "I/O Format Repeat Error",
	63:  "I/O Format Syntax Error",
	64:  "Illegal Path Number",
	65:  "Wrong Number of Subscripts",
	66:  "Non-record-type Operand",
	67:  "Illegal Argument",
	68:  "Illegal Control Structure",
	69:  "Unmatched Control Structure",
	70:  "Illegal FOR Variable",
	71:  "Illegal Expression Type",
	72:  "Illegal Declarative Statement",
	73:  "Array Size Overflow",
	74:  "Undefined Line Number",
	75:  "Multiply-defined Line Number",
	76:  "Multiply-defined Variable",
	77:  "Illegal Input Variable",
	78:  "Seek Out of Range",
	79:  "Missing Data Statement",
}
