//XXX//go:build level2
//XXX// +build level2

package main

// This file was generated by scrape_os9_symbols

const (
	L2_A_AciaP     = 0xFF68 // A.AciaP
	L2_A_ModP      = 0xFF6C // A.ModP
	L2_A_TermV     = 0xFFC0 // A.TermV
	L2_A_V1        = 0xFFC1 // A.V1
	L2_A_V2        = 0xFFC2 // A.V2
	L2_A_V3        = 0xFFC3 // A.V3
	L2_A_V4        = 0xFFC4 // A.V4
	L2_A_V5        = 0xFFC5 // A.V5
	L2_A_V6        = 0xFFC6 // A.V6
	L2_A_V7        = 0xFFC7 // A.V7
	L2_Bt_Block    = 0x003B // Bt.Block
	L2_Bt_Flag     = 0x8A34 // Bt.Flag
	L2_Bt_Offst    = 0x0002 // Bt.Offst
	L2_Bt_Sec      = 0x0000 // Bt.Sec
	L2_Bt_Start    = 0xED00 // Bt.Start
	L2_Bt_Track    = 0x0022 // Bt.Track
	L2_C_BELL      = 0x0007 // C$BELL
	L2_C_BSP       = 0x0008 // C$BSP
	L2_C_Clsall    = 0x0016 // C$Clsall
	L2_C_Clsgr     = 0x0015 // C$Clsgr
	L2_C_COMA      = 0x002C // C$COMA
	L2_C_CR        = 0x000D // C$CR
	L2_C_DEL       = 0x0018 // C$DEL
	L2_C_DELETE    = 0x0010 // C$DELETE
	L2_C_DWN       = 0x001F // C$DWN
	L2_C_EL        = 0x0005 // C$EL
	L2_C_EOF       = 0x001B // C$EOF
	L2_C_FORM      = 0x000C // C$FORM
	L2_C_HOME      = 0x000B // C$HOME
	L2_C_INSERT    = 0x0011 // C$INSERT
	L2_C_INTR      = 0x0003 // C$INTR
	L2_C_LF        = 0x000A // C$LF
	L2_C_LFT       = 0x001D // C$LFT
	L2_C_NULL      = 0x0000 // C$NULL
	L2_C_PAUS      = 0x0017 // C$PAUS
	L2_C_PERD      = 0x002E // C$PERD
	L2_C_PLINE     = 0x0013 // C$PLINE
	L2_C_QUIT      = 0x0005 // C$QUIT
	L2_C_RARR      = 0x0009 // C$RARR
	L2_C_RGT       = 0x001C // C$RGT
	L2_C_RPET      = 0x0001 // C$RPET
	L2_C_RPRT      = 0x0004 // C$RPRT
	L2_C_SHRARR    = 0x0019 // C$SHRARR
	L2_C_SI        = 0x000F // C$SI
	L2_C_SO        = 0x000E // C$SO
	L2_C_SPAC      = 0x0020 // C$SPAC
	L2_C_UP        = 0x001E // C$UP
	L2_C_XOFF      = 0x0013 // C$XOFF
	L2_C_XON       = 0x0011 // C$XON
	L2_COCO_D      = 0x0001 // COCO.D
	L2_D_GSTA      = 0x0009 // D$GSTA
	L2_D_INIT      = 0x0000 // D$INIT
	L2_D_PSTA      = 0x000C // D$PSTA
	L2_D_READ      = 0x0003 // D$READ
	L2_D_TERM      = 0x000F // D$TERM
	L2_D_WRIT      = 0x0006 // D$WRIT
	L2_D_AltIRQ    = 0x00B2 // D.AltIRQ
	L2_D_AProcQ    = 0x0052 // D.AProcQ
	L2_D_BlkMap    = 0x0040 // D.BlkMap
	L2_D_Boot      = 0x0031 // D.Boot
	L2_D_BORDR     = 0x009A // D.BORDR
	L2_D_BtBug     = 0x005E // D.BtBug
	L2_D_BtPtr     = 0x0036 // D.BtPtr
	L2_D_BtSz      = 0x0038 // D.BtSz
	L2_D_CBStrt    = 0x0071 // D.CBStrt
	L2_D_CCMem     = 0x00A5 // D.CCMem
	L2_D_CCStk     = 0x00A7 // D.CCStk
	L2_D_CldRes    = 0x005C // D.CldRes
	L2_D_Clock     = 0x00E0 // D.Clock
	L2_D_Clock2    = 0x00B6 // D.Clock2
	L2_D_CLTb      = 0x00B0 // D.CLTb
	L2_D_COCOXT    = 0x0009 // D.COCOXT
	L2_D_Crash     = 0x006B // D.Crash
	L2_D_CRC       = 0x003B // D.CRC
	L2_D_Day       = 0x002A // D.Day
	L2_D_Daywk     = 0x0034 // D.Daywk
	L2_D_DbgMem    = 0x000A // D.DbgMem
	L2_D_DevTbl    = 0x0080 // D.DevTbl
	L2_D_DMAReq    = 0x008A // D.DMAReq
	L2_D_DWSrvID   = 0x0010 // D.DWSrvID
	L2_D_DWStat    = 0x000E // D.DWStat
	L2_D_DWSubAddr = 0x000C // D.DWSubAddr
	L2_D_ErrCod    = 0x0033 // D.ErrCod
	L2_D_ErrRst    = 0x00EE // D.ErrRst
	L2_D_FIRQ      = 0x00F6 // D.FIRQ
	L2_D_Flip0     = 0x00A9 // D.Flip0
	L2_D_Flip1     = 0x00AB // D.Flip1
	L2_D_FRQER     = 0x0093 // D.FRQER
	L2_D_GPoll     = 0x00B4 // D.GPoll
	L2_D_HINIT     = 0x0090 // D.HINIT
	L2_D_HOFF0     = 0x009F // D.HOFF0
	L2_D_Hour      = 0x002B // D.Hour
	L2_D_Init      = 0x0024 // D.Init
	L2_D_IRQ       = 0x00F8 // D.IRQ
	L2_D_IRQER     = 0x0092 // D.IRQER
	L2_D_IRQS      = 0x00AF // D.IRQS
	L2_D_MemSz     = 0x00A3 // D.MemSz
	L2_D_Min       = 0x002C // D.Min
	L2_D_ModDAT    = 0x005A // D.ModDAT
	L2_D_ModDir    = 0x0044 // D.ModDir
	L2_D_ModEnd    = 0x0058 // D.ModEnd
	L2_D_Month     = 0x0029 // D.Month
	L2_D_MotOn     = 0x0032 // D.MotOn
	L2_D_NMI       = 0x00FC // D.NMI
	L2_D_Pipe      = 0x0061 // D.Pipe
	L2_D_Poll      = 0x0026 // D.Poll
	L2_D_PolTbl    = 0x0082 // D.PolTbl
	L2_D_PrcDBT    = 0x0048 // D.PrcDBT
	L2_D_Proc      = 0x0050 // D.Proc
	L2_D_PthDBT    = 0x0088 // D.PthDBT
	L2_D_QCnt      = 0x007C // D.QCnt
	L2_D_QIRQ      = 0x003F // D.QIRQ
	L2_D_Quick     = 0x003E // D.Quick
	L2_D_RESV1     = 0x0096 // D.RESV1
	L2_D_RESV2     = 0x0097 // D.RESV2
	L2_D_RESV3     = 0x009B // D.RESV3
	L2_D_Sec       = 0x002D // D.Sec
	L2_D_Slice     = 0x002F // D.Slice
	L2_D_Speed     = 0x00A0 // D.Speed
	L2_D_SProcQ    = 0x0056 // D.SProcQ
	L2_D_SSTskN    = 0x00A4 // D.SSTskN
	L2_D_SvcIRQ    = 0x00CE // D.SvcIRQ
	L2_D_SWI       = 0x00FA // D.SWI
	L2_D_SWI2      = 0x00F4 // D.SWI2
	L2_D_SWI3      = 0x00F2 // D.SWI3
	L2_D_SWPage    = 0x0003 // D.SWPage
	L2_D_SysDAT    = 0x004C // D.SysDAT
	L2_D_SysDis    = 0x00C2 // D.SysDis
	L2_D_SysIRQ    = 0x00C4 // D.SysIRQ
	L2_D_SysMem    = 0x004E // D.SysMem
	L2_D_SysPrc    = 0x004A // D.SysPrc
	L2_D_SysStk    = 0x00CC // D.SysStk
	L2_D_SysSvc    = 0x00C0 // D.SysSvc
	L2_D_SysTsk    = 0x00D0 // D.SysTsk
	L2_D_SysVec    = 0x00F0 // D.SysVec
	L2_D_Task1N    = 0x003D // D.Task1N
	L2_D_Tasks     = 0x0020 // D.Tasks
	L2_D_Tenths    = 0x003C // D.Tenths
	L2_D_Tick      = 0x002E // D.Tick
	L2_D_Time      = 0x0028 // D.Time
	L2_D_TIMLS     = 0x0095 // D.TIMLS
	L2_D_TIMMS     = 0x0094 // D.TIMMS
	L2_D_TINIT     = 0x0091 // D.TINIT
	L2_D_TkCnt     = 0x0035 // D.TkCnt
	L2_D_TmpDAT    = 0x0022 // D.TmpDAT
	L2_D_TskIPt    = 0x00A1 // D.TskIPt
	L2_D_TSlice    = 0x0030 // D.TSlice
	L2_D_UsrDis    = 0x00C8 // D.UsrDis
	L2_D_UsrIRQ    = 0x00CA // D.UsrIRQ
	L2_D_UsrSvc    = 0x00C6 // D.UsrSvc
	L2_D_VIDMD     = 0x0098 // D.VIDMD
	L2_D_VIDRS     = 0x0099 // D.VIDRS
	L2_D_VIRQ      = 0x00AD // D.VIRQ
	L2_D_VOFF0     = 0x009E // D.VOFF0
	L2_D_VOFF1     = 0x009D // D.VOFF1
	L2_D_VOFF2     = 0x009C // D.VOFF2
	L2_D_WDAddr    = 0x0000 // D.WDAddr
	L2_D_WDBtDr    = 0x0002 // D.WDBtDr
	L2_D_WProcQ    = 0x0054 // D.WProcQ
	L2_D_XFIRQ     = 0x00E6 // D.XFIRQ
	L2_D_XIRQ      = 0x00E8 // D.XIRQ
	L2_D_XNMI      = 0x00EC // D.XNMI
	L2_D_XSWI      = 0x00EA // D.XSWI
	L2_D_XSWI2     = 0x00E4 // D.XSWI2
	L2_D_XSWI3     = 0x00E2 // D.XSWI3
	L2_D_Year      = 0x0028 // D.Year
	L2_DAT_BlCt    = 0x0008 // DAT.BlCt
	L2_DAT_BlMx    = 0x003F // DAT.BlMx
	L2_DAT_BlSz    = 0x2000 // DAT.BlSz
	L2_DAT_BMSz    = 0x0040 // DAT.BMSz
	L2_DAT_Free    = 0x333E // DAT.Free
	L2_DAT_ImSz    = 0x0010 // DAT.ImSz
	L2_DAT_Regs    = 0xFFA0 // DAT.Regs
	L2_DAT_Task    = 0xFF91 // DAT.Task
	L2_DAT_TkCt    = 0x0020 // DAT.TkCt
	L2_DAT_WrEn    = 0x0000 // DAT.WrEn
	L2_DAT_WrPr    = 0x0000 // DAT.WrPr
	L2_DD_ATT      = 0x000D // DD.ATT
	L2_DD_BIT      = 0x0006 // DD.BIT
	L2_DD_BSZ      = 0x0018 // DD.BSZ
	L2_DD_BT       = 0x0015 // DD.BT
	L2_DD_DAT      = 0x001A // DD.DAT
	L2_DD_DIR      = 0x0008 // DD.DIR
	L2_DD_DSK      = 0x000E // DD.DSK
	L2_DD_FMT      = 0x0010 // DD.FMT
	L2_DD_MAP      = 0x0004 // DD.MAP
	L2_DD_NAM      = 0x001F // DD.NAM
	L2_DD_OPT      = 0x003F // DD.OPT
	L2_DD_OWN      = 0x000B // DD.OWN
	L2_DD_RES      = 0x0013 // DD.RES
	L2_DD_SIZ      = 0x0015 // DD.SIZ
	L2_DD_SPT      = 0x0011 // DD.SPT
	L2_DD_TKS      = 0x0003 // DD.TKS
	L2_DD_TOT      = 0x0000 // DD.TOT
	L2_DIR_        = 0x0080 // DIR.
	L2_DIR_FD      = 0x001D // DIR.FD
	L2_DIR_NM      = 0x0000 // DIR.NM
	L2_DIR_SZ      = 0x0020 // DIR.SZ
	L2_DNS_DTD     = 0x0002 // DNS.DTD
	L2_DNS_FM      = 0x0000 // DNS.FM
	L2_DNS_FM0     = 0x0000 // DNS.FM0
	L2_DNS_MFM     = 0x0001 // DNS.MFM
	L2_DNS_MFM0    = 0x0004 // DNS.MFM0
	L2_DNS_STD     = 0x0000 // DNS.STD
	L2_DT_CDFM     = 0x0005 // DT.CDFM
	L2_DT_NFM      = 0x0004 // DT.NFM
	L2_DT_Pipe     = 0x0002 // DT.Pipe
	L2_DT_RBF      = 0x0001 // DT.RBF
	L2_DT_RFM      = 0x0006 // DT.RFM
	L2_DT_SBF      = 0x0003 // DT.SBF
	L2_DT_SCF      = 0x0000 // DT.SCF
	L2_E_Alias     = 0x00C7 // E$Alias
	L2_E_ArrOvf    = 0x0049 // E$ArrOvf
	L2_E_BadBuf    = 0x00C2 // E$BadBuf
	L2_E_BMCRC     = 0x00E8 // E$BMCRC
	L2_E_BMHP      = 0x00EC // E$BMHP
	L2_E_BMID      = 0x00CD // E$BMID
	L2_E_BMode     = 0x00CB // E$BMode
	L2_E_BNam      = 0x00EB // E$BNam
	L2_E_BPAddr    = 0x00D2 // E$BPAddr
	L2_E_BPNam     = 0x00D7 // E$BPNam
	L2_E_BPNum     = 0x00C9 // E$BPNum
	L2_E_BPrcID    = 0x00E0 // E$BPrcID
	L2_E_BTyp      = 0x00F9 // E$BTyp
	L2_E_BufSiz    = 0x00BF // E$BufSiz
	L2_E_Bug       = 0x00BE // E$Bug
	L2_E_CEF       = 0x00DA // E$CEF
	L2_E_CRC       = 0x00F3 // E$CRC
	L2_E_DeadLk    = 0x00FE // E$DeadLk
	L2_E_DelSP     = 0x00DF // E$DelSP
	L2_E_DevBsy    = 0x00FA // E$DevBsy
	L2_E_DevOvf    = 0x00CC // E$DevOvf
	L2_E_DIDC      = 0x00FB // E$DIDC
	L2_E_DimLrg    = 0x0019 // E$DimLrg
	L2_E_DirFul    = 0x00CE // E$DirFul
	L2_E_DivZer    = 0x002D // E$DivZer
	L2_E_Dn        = 0x00C6 // E$Dn
	L2_E_DNE       = 0x00EE // E$DNE
	L2_E_EndQou    = 0x0029 // E$EndQou
	L2_E_EOF       = 0x00D3 // E$EOF
	L2_E_ExcVrb    = 0x000B // E$ExcVrb
	L2_E_FltOvf    = 0x0032 // E$FltOvf
	L2_E_FNA       = 0x00D6 // E$FNA
	L2_E_Full      = 0x00F8 // E$Full
	L2_E_HangUp    = 0x00DC // E$HangUp
	L2_E_IBA       = 0x00DB // E$IBA
	L2_E_IChRef    = 0x000E // E$IChRef
	L2_E_ICoord    = 0x00BD // E$ICoord
	L2_E_ICOvf     = 0x000D // E$ICOvf
	L2_E_IForkP    = 0x00E6 // E$IForkP
	L2_E_IllA      = 0x0043 // E$IllA
	L2_E_IllArg    = 0x00BB // E$IllArg
	L2_E_IllCmd    = 0x00C0 // E$IllCmd
	L2_E_IllCnt    = 0x0044 // E$IllCnt
	L2_E_IllDec    = 0x0048 // E$IllDec
	L2_E_IllDim    = 0x0015 // E$IllDim
	L2_E_IllExp    = 0x0047 // E$IllExp
	L2_E_IllFOR    = 0x0046 // E$IllFOR
	L2_E_IllInp    = 0x003D // E$IllInp
	L2_E_IllIVr    = 0x004D // E$IllIVr
	L2_E_IllLit    = 0x0016 // E$IllLit
	L2_E_IllMod    = 0x000F // E$IllMod
	L2_E_IllNum    = 0x0010 // E$IllNum
	L2_E_IllOpd    = 0x0012 // E$IllOpd
	L2_E_IllOpr    = 0x0013 // E$IllOpr
	L2_E_IllPNm    = 0x0040 // E$IllPNm
	L2_E_IllPrf    = 0x0011 // E$IllPrf
	L2_E_IllRet    = 0x0017 // E$IllRet
	L2_E_IllRFN    = 0x0014 // E$IllRFN
	L2_E_IllSfx    = 0x0018 // E$IllSfx
	L2_E_IllStC    = 0x000C // E$IllStC
	L2_E_IOConv    = 0x003C // E$IOConv
	L2_E_IOFRpt    = 0x003E // E$IOFRpt
	L2_E_IOFSyn    = 0x003F // E$IOFSyn
	L2_E_IOMism    = 0x003A // E$IOMism
	L2_E_IONum     = 0x003B // E$IONum
	L2_E_IPrcID    = 0x00E0 // E$IPrcID
	L2_E_ISWI      = 0x00E3 // E$ISWI
	L2_E_IWDef     = 0x00C3 // E$IWDef
	L2_E_IWTyp     = 0x00B7 // E$IWTyp
	L2_E_KwnMod    = 0x00E7 // E$KwnMod
	L2_E_LinLrg    = 0x001A // E$LinLrg
	L2_E_LnComp    = 0x0033 // E$LnComp
	L2_E_Lock      = 0x00FC // E$Lock
	L2_E_MemFul    = 0x00CF // E$MemFul
	L2_E_MFull     = 0x0020 // E$MFull
	L2_E_MltLin    = 0x004B // E$MltLin
	L2_E_MltVar    = 0x004C // E$MltVar
	L2_E_MNF       = 0x00DD // E$MNF
	L2_E_ModBsy    = 0x00D1 // E$ModBsy
	L2_E_MulPrc    = 0x002C // E$MulPrc
	L2_E_NEMod     = 0x00EA // E$NEMod
	L2_E_NES       = 0x00D5 // E$NES
	L2_E_NFont     = 0x00B9 // E$NFont
	L2_E_NoAssg    = 0x001B // E$NoAssg
	L2_E_NoChld    = 0x00E2 // E$NoChld
	L2_E_NoComa    = 0x001D // E$NoComa
	L2_E_NoData    = 0x004F // E$NoData
	L2_E_NoDim     = 0x001E // E$NoDim
	L2_E_NoDO      = 0x001F // E$NoDO
	L2_E_NoGoto    = 0x0021 // E$NoGoto
	L2_E_NoLPar    = 0x0022 // E$NoLPar
	L2_E_NoLRef    = 0x0023 // E$NoLRef
	L2_E_NonRcO    = 0x0042 // E$NonRcO
	L2_E_NoOprd    = 0x0024 // E$NoOprd
	L2_E_NoPath    = 0x001C // E$NoPath
	L2_E_NoRAM     = 0x00ED // E$NoRAM
	L2_E_NoRout    = 0x0030 // E$NoRout
	L2_E_NoRPar    = 0x0025 // E$NoRPar
	L2_E_NoTask    = 0x00EF // E$NoTask
	L2_E_NoTHEN    = 0x0026 // E$NoTHEN
	L2_E_NoTO      = 0x0027 // E$NoTO
	L2_E_NotRdy    = 0x00F6 // E$NotRdy
	L2_E_NoVRef    = 0x0028 // E$NoVRef
	L2_E_ParmEr    = 0x0038 // E$ParmEr
	L2_E_PNNF      = 0x00D8 // E$PNNF
	L2_E_Poll      = 0x00CA // E$Poll
	L2_E_PrcAbt    = 0x00E4 // E$PrcAbt
	L2_E_PrcFul    = 0x00E5 // E$PrcFul
	L2_E_PthFul    = 0x00C8 // E$PthFul
	L2_E_Read      = 0x00F4 // E$Read
	L2_E_Sect      = 0x00F1 // E$Sect
	L2_E_Seek      = 0x00F7 // E$Seek
	L2_E_SeekRg    = 0x004E // E$SeekRg
	L2_E_Share     = 0x00FD // E$Share
	L2_E_SLF       = 0x00D9 // E$SLF
	L2_E_StkOvf    = 0x00BA // E$StkOvf
	L2_E_StrOvf    = 0x002F // E$StrOvf
	L2_E_SubLrg    = 0x002A // E$SubLrg
	L2_E_SubOvf    = 0x0035 // E$SubOvf
	L2_E_SubRng    = 0x0037 // E$SubRng
	L2_E_SubUnd    = 0x0036 // E$SubUnd
	L2_E_SysOvf    = 0x0039 // E$SysOvf
	L2_E_TblFul    = 0x00C1 // E$TblFul
	L2_E_TypMis    = 0x002E // E$TypMis
	L2_E_UndLin    = 0x004A // E$UndLin
	L2_E_UndVar    = 0x0031 // E$UndVar
	L2_E_Unit      = 0x00F0 // E$Unit
	L2_E_UnkPrc    = 0x002B // E$UnkPrc
	L2_E_UnkSvc    = 0x00D0 // E$UnkSvc
	L2_E_UnkSym    = 0x000A // E$UnkSym
	L2_E_UnmCnt    = 0x0045 // E$UnmCnt
	L2_E_Up        = 0x00C5 // E$Up
	L2_E_USigP     = 0x00E9 // E$USigP
	L2_E_ValRng    = 0x0034 // E$ValRng
	L2_E_WADef     = 0x00B8 // E$WADef
	L2_E_WP        = 0x00F2 // E$WP
	L2_E_Write     = 0x00F5 // E$Write
	L2_E_WrSub     = 0x0041 // E$WrSub
	L2_E_WUndef    = 0x00C4 // E$WUndef
	L2_EXEC_       = 0x0004 // EXEC.
	L2_F_Alarm     = 0x001E // F$Alarm
	L2_F_AlHRAM    = 0x0053 // F$AlHRAM
	L2_F_All64     = 0x0030 // F$All64
	L2_F_AllBit    = 0x0013 // F$AllBit
	L2_F_AllImg    = 0x003A // F$AllImg
	L2_F_AllPrc    = 0x004B // F$AllPrc
	L2_F_AllRAM    = 0x0039 // F$AllRAM
	L2_F_AllTsk    = 0x003F // F$AllTsk
	L2_F_AProc     = 0x002C // F$AProc
	L2_F_Boot      = 0x0035 // F$Boot
	L2_F_BtMem     = 0x0036 // F$BtMem
	L2_F_Chain     = 0x0005 // F$Chain
	L2_F_ClrBlk    = 0x0050 // F$ClrBlk
	L2_F_CmpNam    = 0x0011 // F$CmpNam
	L2_F_CpyMem    = 0x001B // F$CpyMem
	L2_F_CRC       = 0x0017 // F$CRC
	L2_F_CRCMod    = 0x0055 // F$CRCMod
	L2_F_DATLog    = 0x0044 // F$DATLog
	L2_F_DATTmp    = 0x0045 // F$DATTmp
	L2_F_Debug     = 0x0023 // F$Debug
	L2_F_DelBit    = 0x0014 // F$DelBit
	L2_F_DelImg    = 0x003B // F$DelImg
	L2_F_DelPrc    = 0x004C // F$DelPrc
	L2_F_DelRAM    = 0x0051 // F$DelRAM
	L2_F_DelTsk    = 0x0040 // F$DelTsk
	L2_F_ELink     = 0x004D // F$ELink
	L2_F_Exit      = 0x0006 // F$Exit
	L2_F_Find64    = 0x002F // F$Find64
	L2_F_FModul    = 0x004E // F$FModul
	L2_F_Fork      = 0x0003 // F$Fork
	L2_F_FreeHB    = 0x003E // F$FreeHB
	L2_F_FreeLB    = 0x003D // F$FreeLB
	L2_F_GBlkMp    = 0x0019 // F$GBlkMp
	L2_F_GCMDir    = 0x0052 // F$GCMDir
	L2_F_GModDr    = 0x001A // F$GModDr
	L2_F_GPrDsc    = 0x0018 // F$GPrDsc
	L2_F_GProcP    = 0x0037 // F$GProcP
	L2_F_Icpt      = 0x0009 // F$Icpt
	L2_F_ID        = 0x000C // F$ID
	L2_F_IODel     = 0x0033 // F$IODel
	L2_F_IOQu      = 0x002B // F$IOQu
	L2_F_IRQ       = 0x002A // F$IRQ
	L2_F_LDABX     = 0x0049 // F$LDABX
	L2_F_LDAXY     = 0x0046 // F$LDAXY
	L2_F_LDAXYP    = 0x0047 // F$LDAXYP
	L2_F_LDDDXY    = 0x0048 // F$LDDDXY
	L2_F_Link      = 0x0000 // F$Link
	L2_F_Load      = 0x0001 // F$Load
	L2_F_MapBlk    = 0x004F // F$MapBlk
	L2_F_Mem       = 0x0007 // F$Mem
	L2_F_Move      = 0x0038 // F$Move
	L2_F_NMLink    = 0x0021 // F$NMLink
	L2_F_NMLoad    = 0x0022 // F$NMLoad
	L2_F_NProc     = 0x002D // F$NProc
	L2_F_NVRAM     = 0x0071 // F$NVRAM
	L2_F_PErr      = 0x000F // F$PErr
	L2_F_PrsNam    = 0x0010 // F$PrsNam
	L2_F_ReBoot    = 0x0054 // F$ReBoot
	L2_F_RegDmp    = 0x0070 // F$RegDmp
	L2_F_RelTsk    = 0x0043 // F$RelTsk
	L2_F_ResTsk    = 0x0042 // F$ResTsk
	L2_F_Ret64     = 0x0031 // F$Ret64
	L2_F_SchBit    = 0x0012 // F$SchBit
	L2_F_Send      = 0x0008 // F$Send
	L2_F_SetImg    = 0x003C // F$SetImg
	L2_F_SetTsk    = 0x0041 // F$SetTsk
	L2_F_Sleep     = 0x000A // F$Sleep
	L2_F_SLink     = 0x0034 // F$SLink
	L2_F_SPrior    = 0x000D // F$SPrior
	L2_F_SRqMem    = 0x0028 // F$SRqMem
	L2_F_SRtMem    = 0x0029 // F$SRtMem
	L2_F_SSpd      = 0x000B // F$SSpd
	L2_F_SSvc      = 0x0032 // F$SSvc
	L2_F_SSWI      = 0x000E // F$SSWI
	L2_F_STABX     = 0x004A // F$STABX
	L2_F_STime     = 0x0016 // F$STime
	L2_F_SUser     = 0x001C // F$SUser
	L2_F_TimAlm    = 0x0026 // F$TimAlm
	L2_F_Time      = 0x0015 // F$Time
	L2_F_TPS       = 0x0025 // F$TPS
	L2_F_UnLink    = 0x0002 // F$UnLink
	L2_F_UnLoad    = 0x001D // F$UnLoad
	L2_F_VBlock    = 0x0057 // F$VBlock
	L2_F_VIRQ      = 0x0027 // F$VIRQ
	L2_F_VModul    = 0x002E // F$VModul
	L2_F_Wait      = 0x0004 // F$Wait
	L2_F_XTime     = 0x0056 // F$XTime
	L2_FD_ATT      = 0x0000 // FD.ATT
	L2_FD_Creat    = 0x000D // FD.Creat
	L2_FD_DAT      = 0x0003 // FD.DAT
	L2_FD_LNK      = 0x0008 // FD.LNK
	L2_FD_LS1      = 0x00FB // FD.LS1
	L2_FD_LS2      = 0x00FA // FD.LS2
	L2_FD_OWN      = 0x0001 // FD.OWN
	L2_FD_SEG      = 0x0010 // FD.SEG
	L2_FD_SIZ      = 0x0009 // FD.SIZ
	L2_FDSL_A      = 0x0000 // FDSL.A
	L2_FDSL_B      = 0x0003 // FDSL.B
	L2_FDSL_S      = 0x0005 // FDSL.S
	L2_FMT_DNS     = 0x0002 // FMT.DNS
	L2_FMT_SIDE    = 0x0001 // FMT.SIDE
	L2_FMT_T0DN    = 0x0020 // FMT.T0DN
	L2_FMT_TDNS    = 0x0004 // FMT.TDNS
	L2_HW_Page     = 0x0007 // HW.Page
	L2_I_Attach    = 0x0080 // I$Attach
	L2_I_ChgDir    = 0x0086 // I$ChgDir
	L2_I_Close     = 0x008F // I$Close
	L2_I_Create    = 0x0083 // I$Create
	L2_I_Delete    = 0x0087 // I$Delete
	L2_I_DeletX    = 0x0090 // I$DeletX
	L2_I_Detach    = 0x0081 // I$Detach
	L2_I_Dup       = 0x0082 // I$Dup
	L2_I_GetStt    = 0x008D // I$GetStt
	L2_I_MakDir    = 0x0085 // I$MakDir
	L2_I_Open      = 0x0084 // I$Open
	L2_I_Read      = 0x0089 // I$Read
	L2_I_ReadLn    = 0x008B // I$ReadLn
	L2_I_Seek      = 0x0088 // I$Seek
	L2_I_SetStt    = 0x008E // I$SetStt
	L2_I_Write     = 0x008A // I$Write
	L2_I_WritLn    = 0x008C // I$WritLn
	L2_ISIZ_       = 0x0020 // ISIZ.
	L2_IT_ALF      = 0x0017 // IT.ALF
	L2_IT_BAU      = 0x0027 // IT.BAU
	L2_IT_BDC      = 0x0035 // IT.BDC
	L2_IT_BGC      = 0x0034 // IT.BGC
	L2_IT_BSE      = 0x0024 // IT.BSE
	L2_IT_BSO      = 0x0014 // IT.BSO
	L2_IT_BSP      = 0x001B // IT.BSP
	L2_IT_COL      = 0x002C // IT.COL
	L2_IT_CPX      = 0x0031 // IT.CPX
	L2_IT_CPY      = 0x0032 // IT.CPY
	L2_IT_CYL      = 0x0017 // IT.CYL
	L2_IT_D2P      = 0x0028 // IT.D2P
	L2_IT_DEL      = 0x001C // IT.DEL
	L2_IT_DLO      = 0x0015 // IT.DLO
	L2_IT_DNS      = 0x0016 // IT.DNS
	L2_IT_DRV      = 0x0013 // IT.DRV
	L2_IT_DTP      = 0x0012 // IT.DTP
	L2_IT_DUP      = 0x0020 // IT.DUP
	L2_IT_DVC      = 0x0012 // IT.DVC
	L2_IT_EKO      = 0x0016 // IT.EKO
	L2_IT_EOF      = 0x001E // IT.EOF
	L2_IT_EOR      = 0x001D // IT.EOR
	L2_IT_Exten    = 0x0022 // IT.Exten
	L2_IT_FGC      = 0x0033 // IT.FGC
	L2_IT_ILV      = 0x001F // IT.ILV
	L2_IT_INT      = 0x0022 // IT.INT
	L2_IT_LLDRV    = 0x0028 // IT.LLDRV
	L2_IT_MPI      = 0x002A // IT.MPI
	L2_IT_NUL      = 0x0018 // IT.NUL
	L2_IT_OFS      = 0x0026 // IT.OFS
	L2_IT_OVF      = 0x0025 // IT.OVF
	L2_IT_PAG      = 0x001A // IT.PAG
	L2_IT_PAR      = 0x0026 // IT.PAR
	L2_IT_PAU      = 0x0019 // IT.PAU
	L2_IT_PSC      = 0x0021 // IT.PSC
	L2_IT_QUT      = 0x0023 // IT.QUT
	L2_IT_ROW      = 0x002D // IT.ROW
	L2_IT_RPR      = 0x001F // IT.RPR
	L2_IT_RWC      = 0x0028 // IT.RWC
	L2_IT_SAS      = 0x0020 // IT.SAS
	L2_IT_SCT      = 0x001B // IT.SCT
	L2_IT_SID      = 0x0019 // IT.SID
	L2_IT_SOFF1    = 0x0025 // IT.SOFF1
	L2_IT_SOFF2    = 0x0026 // IT.SOFF2
	L2_IT_SOFF3    = 0x0027 // IT.SOFF3
	L2_IT_SToff    = 0x0024 // IT.SToff
	L2_IT_STP      = 0x0014 // IT.STP
	L2_IT_STY      = 0x0030 // IT.STY
	L2_IT_T0S      = 0x001D // IT.T0S
	L2_IT_TFM      = 0x0021 // IT.TFM
	L2_IT_TYP      = 0x0015 // IT.TYP
	L2_IT_UPC      = 0x0013 // IT.UPC
	L2_IT_VAL      = 0x002F // IT.VAL
	L2_IT_VFY      = 0x001A // IT.VFY
	L2_IT_WND      = 0x002E // IT.WND
	L2_IT_WPC      = 0x0025 // IT.WPC
	L2_IT_XOFF     = 0x002B // IT.XOFF
	L2_IT_XON      = 0x002A // IT.XON
	L2_IT_XTYP     = 0x002E // IT.XTYP
	L2_M_DTyp      = 0x0012 // M$DTyp
	L2_M_Exec      = 0x0009 // M$Exec
	L2_M_FMgr      = 0x0009 // M$FMgr
	L2_M_ID        = 0x0000 // M$ID
	L2_M_ID1       = 0x0087 // M$ID1
	L2_M_ID12      = 0x87CD // M$ID12
	L2_M_ID2       = 0x00CD // M$ID2
	L2_M_IDSize    = 0x0009 // M$IDSize
	L2_M_Mem       = 0x000B // M$Mem
	L2_M_Mode      = 0x000D // M$Mode
	L2_M_Name      = 0x0004 // M$Name
	L2_M_Opt       = 0x0011 // M$Opt
	L2_M_Parity    = 0x0008 // M$Parity
	L2_M_PDev      = 0x000B // M$PDev
	L2_M_Port      = 0x000E // M$Port
	L2_M_Revs      = 0x0007 // M$Revs
	L2_M_Size      = 0x0002 // M$Size
	L2_M_Type      = 0x0006 // M$Type
	L2_MD_ESize    = 0x0008 // MD$ESize
	L2_MD_Link     = 0x0006 // MD$Link
	L2_MD_MBSiz    = 0x0002 // MD$MBSiz
	L2_MD_MPDAT    = 0x0000 // MD$MPDAT
	L2_MD_MPtr     = 0x0004 // MD$MPtr
	L2_MPI_Slct    = 0xFF7F // MPI.Slct
	L2_MPI_Slot    = 0x0003 // MPI.Slot
	L2_P_Age       = 0x000B // P$Age
	L2_P_Alarm     = 0x00C3 // P$Alarm
	L2_P_CID       = 0x0003 // P$CID
	L2_P_DatBeg    = 0x00BD // P$DatBeg
	L2_P_DATImg    = 0x0040 // P$DATImg
	L2_P_DeadLk    = 0x001E // P$DeadLk
	L2_P_DIO       = 0x0020 // P$DIO
	L2_P_FCalls    = 0x00B5 // P$FCalls
	L2_P_ICalls    = 0x00B9 // P$ICalls
	L2_P_ID        = 0x0000 // P$ID
	L2_P_IOQN      = 0x0010 // P$IOQN
	L2_P_IOQP      = 0x000F // P$IOQP
	L2_P_Links     = 0x0080 // P$Links
	L2_P_NIO       = 0x00A0 // P$NIO
	L2_P_PagCnt    = 0x0007 // P$PagCnt
	L2_P_Path      = 0x0030 // P$Path
	L2_P_PID       = 0x0001 // P$PID
	L2_P_PModul    = 0x0011 // P$PModul
	L2_P_Prior     = 0x000A // P$Prior
	L2_P_Queue     = 0x000D // P$Queue
	L2_P_SelP      = 0x00AC // P$SelP
	L2_P_SID       = 0x0002 // P$SID
	L2_P_SigDat    = 0x001C // P$SigDat
	L2_P_Signal    = 0x0019 // P$Signal
	L2_P_SigVec    = 0x001A // P$SigVec
	L2_P_Size      = 0x0200 // P$Size
	L2_P_SP        = 0x0004 // P$SP
	L2_P_Stack     = 0x0200 // P$Stack
	L2_P_State     = 0x000C // P$State
	L2_P_STicks    = 0x00B1 // P$STicks
	L2_P_SWI       = 0x0013 // P$SWI
	L2_P_SWI2      = 0x0015 // P$SWI2
	L2_P_SWI3      = 0x0017 // P$SWI3
	L2_P_Task      = 0x0006 // P$Task
	L2_P_TimBeg    = 0x00C0 // P$TimBeg
	L2_P_User      = 0x0008 // P$User
	L2_P_UTicks    = 0x00AD // P$UTicks
	L2_PD_ALF      = 0x0025 // PD.ALF
	L2_PD_ATT      = 0x0033 // PD.ATT
	L2_PD_BAU      = 0x0035 // PD.BAU
	L2_PD_BSE      = 0x0032 // PD.BSE
	L2_PD_BSO      = 0x0022 // PD.BSO
	L2_PD_BSP      = 0x0029 // PD.BSP
	L2_PD_BUF      = 0x0008 // PD.BUF
	L2_PD_CNT      = 0x0002 // PD.CNT
	L2_PD_CP       = 0x000B // PD.CP
	L2_PD_CPR      = 0x0005 // PD.CPR
	L2_PD_CYL      = 0x0025 // PD.CYL
	L2_PD_D2P      = 0x0036 // PD.D2P
	L2_PD_DCP      = 0x003A // PD.DCP
	L2_PD_DEL      = 0x002A // PD.DEL
	L2_PD_DEV      = 0x0003 // PD.DEV
	L2_PD_DFD      = 0x0037 // PD.DFD
	L2_PD_DLO      = 0x0023 // PD.DLO
	L2_PD_DNS      = 0x0024 // PD.DNS
	L2_PD_DRV      = 0x0021 // PD.DRV
	L2_PD_DSK      = 0x001C // PD.DSK
	L2_PD_DTB      = 0x001E // PD.DTB
	L2_PD_DTP      = 0x0020 // PD.DTP
	L2_PD_DUP      = 0x002E // PD.DUP
	L2_PD_DV2      = 0x000A // PD.DV2
	L2_PD_DVT      = 0x003E // PD.DVT
	L2_PD_EKO      = 0x0024 // PD.EKO
	L2_PD_EOF      = 0x002C // PD.EOF
	L2_PD_EOR      = 0x002B // PD.EOR
	L2_PD_ERR      = 0x003A // PD.ERR
	L2_PD_Exten    = 0x0030 // PD.Exten
	L2_PD_FD       = 0x0034 // PD.FD
	L2_PD_FST      = 0x000A // PD.FST
	L2_PD_ILV      = 0x002D // PD.ILV
	L2_PD_INT      = 0x0030 // PD.INT
	L2_PD_MAX      = 0x000D // PD.MAX
	L2_PD_MIN      = 0x000F // PD.MIN
	L2_PD_MOD      = 0x0001 // PD.MOD
	L2_PD_NUL      = 0x0026 // PD.NUL
	L2_PD_OPT      = 0x0020 // PD.OPT
	L2_PD_OVF      = 0x0033 // PD.OVF
	L2_PD_PAG      = 0x0028 // PD.PAG
	L2_PD_PAR      = 0x0034 // PD.PAR
	L2_PD_PAU      = 0x0027 // PD.PAU
	L2_PD_PD       = 0x0000 // PD.PD
	L2_PD_PLP      = 0x003D // PD.PLP
	L2_PD_PSC      = 0x002F // PD.PSC
	L2_PD_PST      = 0x003F // PD.PST
	L2_PD_QUT      = 0x0031 // PD.QUT
	L2_PD_RAW      = 0x000C // PD.RAW
	L2_PD_RGS      = 0x0006 // PD.RGS
	L2_PD_RPR      = 0x002D // PD.RPR
	L2_PD_SAS      = 0x002E // PD.SAS
	L2_PD_SBL      = 0x0013 // PD.SBL
	L2_PD_SBP      = 0x0016 // PD.SBP
	L2_PD_SCT      = 0x0029 // PD.SCT
	L2_PD_SID      = 0x0027 // PD.SID
	L2_PD_SIZ      = 0x000F // PD.SIZ
	L2_PD_SMF      = 0x000A // PD.SMF
	L2_PD_SSZ      = 0x0019 // PD.SSZ
	L2_PD_STM      = 0x0012 // PD.STM
	L2_PD_SToff    = 0x0032 // PD.SToff
	L2_PD_STP      = 0x0022 // PD.STP
	L2_PD_STS      = 0x0010 // PD.STS
	L2_PD_T0S      = 0x002B // PD.T0S
	L2_PD_TBL      = 0x003B // PD.TBL
	L2_PD_TFM      = 0x002F // PD.TFM
	L2_PD_TYP      = 0x0023 // PD.TYP
	L2_PD_UPC      = 0x0021 // PD.UPC
	L2_PD_VFY      = 0x0028 // PD.VFY
	L2_PD_XOFF     = 0x0039 // PD.XOFF
	L2_PD_XON      = 0x0038 // PD.XON
	L2_PE_Confl    = 0x0005 // PE.Confl
	L2_PE_FilNm    = 0x0020 // PE.FilNm
	L2_PE_HiLck    = 0x000C // PE.HiLck
	L2_PE_Lock     = 0x0007 // PE.Lock
	L2_PE_LoLck    = 0x0008 // PE.LoLck
	L2_PE_NxFil    = 0x0003 // PE.NxFil
	L2_PE_Owner    = 0x0014 // PE.Owner
	L2_PE_PDptr    = 0x0001 // PE.PDptr
	L2_PE_PE       = 0x0000 // PE.PE
	L2_PE_Prior    = 0x0016 // PE.Prior
	L2_PE_Req      = 0x0015 // PE.Req
	L2_PE_SigID    = 0x0018 // PE.SigID
	L2_PE_SigSg    = 0x0017 // PE.SigSg
	L2_PE_TmOut    = 0x0012 // PE.TmOut
	L2_PE_Wait     = 0x0010 // PE.Wait
	L2_PEXEC_      = 0x0020 // PEXEC.
	L2_PREAD_      = 0x0008 // PREAD.
	L2_PST_DCD     = 0x0001 // PST.DCD
	L2_PWRIT_      = 0x0010 // PWRIT.
	L2_Q_FLIP      = 0x0002 // Q$FLIP
	L2_Q_MAP       = 0x0009 // Q$MAP
	L2_Q_MASK      = 0x0003 // Q$MASK
	L2_Q_POLL      = 0x0000 // Q$POLL
	L2_Q_PRTY      = 0x0008 // Q$PRTY
	L2_Q_SERV      = 0x0004 // Q$SERV
	L2_Q_STAT      = 0x0006 // Q$STAT
	L2_R_A         = 0x0001 // R$A
	L2_R_B         = 0x0002 // R$B
	L2_R_CC        = 0x0000 // R$CC
	L2_R_D         = 0x0001 // R$D
	L2_R_DP        = 0x0003 // R$DP
	L2_R_PC        = 0x000A // R$PC
	L2_R_Size      = 0x000C // R$Size
	L2_R_U         = 0x0008 // R$U
	L2_R_X         = 0x0004 // R$X
	L2_R_Y         = 0x0006 // R$Y
	L2_R_Crash     = 0x0111 // R.Crash
	L2_RBF_D       = 0x0001 // RBF.D
	L2_READ_       = 0x0001 // READ.
	L2_S_Abort     = 0x0002 // S$Abort
	L2_S_Alarm     = 0x0005 // S$Alarm
	L2_S_HUP       = 0x0004 // S$HUP
	L2_S_Intrpt    = 0x0003 // S$Intrpt
	L2_S_Kill      = 0x0000 // S$Kill
	L2_S_Wake      = 0x0001 // S$Wake
	L2_S_Window    = 0x0004 // S$Window
	L2_SCF_D       = 0x0001 // SCF.D
	L2_SHARE_      = 0x0040 // SHARE.
	L2_SS_AAGBf    = 0x0080 // SS.AAGBf
	L2_SS_AlfaS    = 0x001C // SS.AlfaS
	L2_SS_AnPal    = 0x009A // SS.AnPal
	L2_SS_ARAM     = 0x00CA // SS.ARAM
	L2_SS_AScrn    = 0x008B // SS.AScrn
	L2_SS_Attr     = 0x001C // SS.Attr
	L2_SS_BlkRd    = 0x0014 // SS.BlkRd
	L2_SS_BlkWr    = 0x0015 // SS.BlkWr
	L2_SS_Break    = 0x001D // SS.Break
	L2_SS_CDRel    = 0x009B // SS.CDRel
	L2_SS_CDSig    = 0x009A // SS.CDSig
	L2_SS_CDSta    = 0x0099 // SS.CDSta
	L2_SS_Close    = 0x002A // SS.Close
	L2_SS_ComSt    = 0x0028 // SS.ComSt
	L2_SS_Cursr    = 0x0025 // SS.Cursr
	L2_SS_DCmd     = 0x000D // SS.DCmd
	L2_SS_DevNm    = 0x000E // SS.DevNm
	L2_SS_DfPal    = 0x0097 // SS.DfPal
	L2_SS_DirEnt   = 0x0020 // SS.DirEnt
	L2_SS_DRAM     = 0x00CB // SS.DRAM
	L2_SS_DRead    = 0x0080 // SS.DRead
	L2_SS_DrvCh    = 0x0086 // SS.DrvCh
	L2_SS_DScrn    = 0x008C // SS.DScrn
	L2_SS_DSize    = 0x0026 // SS.DSize
	L2_SS_DStat    = 0x0012 // SS.DStat
	L2_SS_DWrit    = 0x0080 // SS.DWrit
	L2_SS_ECC      = 0x00B0 // SS.ECC
	L2_SS_ELog     = 0x0019 // SS.ELog
	L2_SS_EOF      = 0x0006 // SS.EOF
	L2_SS_FBRgs    = 0x0096 // SS.FBRgs
	L2_SS_FClr     = 0x0081 // SS.FClr
	L2_SS_FD       = 0x000F // SS.FD
	L2_SS_FDInf    = 0x0020 // SS.FDInf
	L2_SS_Feed     = 0x0009 // SS.Feed
	L2_SS_Fill     = 0x00A0 // SS.Fill
	L2_SS_FndBf    = 0x009B // SS.FndBf
	L2_SS_Frz      = 0x000A // SS.Frz
	L2_SS_FScrn    = 0x008D // SS.FScrn
	L2_SS_FSet     = 0x00C7 // SS.FSet
	L2_SS_FSig     = 0x002C // SS.FSig
	L2_SS_GIP      = 0x0094 // SS.GIP
	L2_SS_GIP2     = 0x0099 // SS.GIP2
	L2_SS_Hist     = 0x00A1 // SS.Hist
	L2_SS_HngUp    = 0x002B // SS.HngUp
	L2_SS_Joy      = 0x0013 // SS.Joy
	L2_SS_KClr     = 0x00C9 // SS.KClr
	L2_SS_KSet     = 0x00C8 // SS.KSet
	L2_SS_KySns    = 0x0027 // SS.KySns
	L2_SS_Link     = 0x0007 // SS.Link
	L2_SS_Lock     = 0x0011 // SS.Lock
	L2_SS_MnSel    = 0x0087 // SS.MnSel
	L2_SS_MOFF     = 0x0082 // SS.MOFF
	L2_SS_Montr    = 0x0092 // SS.Montr
	L2_SS_MoTim    = 0x0083 // SS.MoTim
	L2_SS_Mount    = 0x0082 // SS.Mount
	L2_SS_Mouse    = 0x0089 // SS.Mouse
	L2_SS_MpGPB    = 0x0084 // SS.MpGPB
	L2_SS_MsSig    = 0x008A // SS.MsSig
	L2_SS_Open     = 0x0029 // SS.Open
	L2_SS_Opt      = 0x0000 // SS.Opt
	L2_SS_Palet    = 0x0091 // SS.Palet
	L2_SS_Pos      = 0x0005 // SS.Pos
	L2_SS_PScrn    = 0x008E // SS.PScrn
	L2_SS_RdNet    = 0x0083 // SS.RdNet
	L2_SS_Ready    = 0x0001 // SS.Ready
	L2_SS_Relea    = 0x001B // SS.Relea
	L2_SS_Reset    = 0x0003 // SS.Reset
	L2_SS_Reten    = 0x0016 // SS.Reten
	L2_SS_RFM      = 0x0018 // SS.RFM
	L2_SS_RsBit    = 0x001E // SS.RsBit
	L2_SS_SBar     = 0x0088 // SS.SBar
	L2_SS_ScInf    = 0x008F // SS.ScInf
	L2_SS_ScSiz    = 0x0026 // SS.ScSiz
	L2_SS_ScTyp    = 0x0093 // SS.ScTyp
	L2_SS_SDRD     = 0x0084 // SS.SDRD
	L2_SS_SDWRT    = 0x0084 // SS.SDWRT
	L2_SS_SetMF    = 0x0024 // SS.SetMF
	L2_SS_Size     = 0x0002 // SS.Size
	L2_SS_Sleep    = 0x0085 // SS.Sleep
	L2_SS_SLGBf    = 0x0081 // SS.SLGBf
	L2_SS_Slots    = 0x0085 // SS.Slots
	L2_SS_SPT      = 0x000B // SS.SPT
	L2_SS_SQD      = 0x000C // SS.SQD
	L2_SS_SSig     = 0x001A // SS.SSig
	L2_SS_Ticks    = 0x0010 // SS.Ticks
	L2_SS_Tone     = 0x0098 // SS.Tone
	L2_SS_ULink    = 0x0008 // SS.ULink
	L2_SS_UMBar    = 0x0095 // SS.UMBar
	L2_SS_UnFrz    = 0x0081 // SS.UnFrz
	L2_SS_VarSect  = 0x0012 // SS.VarSect
	L2_SS_VCtr     = 0x0080 // SS.VCtr
	L2_SS_VSig     = 0x0081 // SS.VSig
	L2_SS_WFM      = 0x0017 // SS.WFM
	L2_SS_WnSet    = 0x0086 // SS.WnSet
	L2_SS_WTrk     = 0x0004 // SS.WTrk
	L2_STP_12ms    = 0x0002 // STP.12ms
	L2_STP_20ms    = 0x0001 // STP.20ms
	L2_STP_30ms    = 0x0000 // STP.30ms
	L2_STP_6ms     = 0x0003 // STP.6ms
	L2_TYP_256     = 0x0000 // TYP.256
	L2_TYP_3       = 0x0001 // TYP.3
	L2_TYP_5       = 0x0000 // TYP.5
	L2_TYP_512     = 0x0004 // TYP.512
	L2_TYP_CCF     = 0x0020 // TYP.CCF
	L2_TYP_FLP     = 0x0000 // TYP.FLP
	L2_TYP_HARD    = 0x0080 // TYP.HARD
	L2_TYP_NCCF    = 0x0000 // TYP.NCCF
	L2_TYP_NSF     = 0x0040 // TYP.NSF
	L2_TYP_SBO     = 0x0002 // TYP.SBO
	L2_TYP_SOF     = 0x0000 // TYP.SOF
	L2_TYPH_1024   = 0x0002 // TYPH.1024
	L2_TYPH_2048   = 0x0003 // TYPH.2048
	L2_TYPH_256    = 0x0000 // TYPH.256
	L2_TYPH_512    = 0x0001 // TYPH.512
	L2_TYPH_DRSV   = 0x000C // TYPH.DRSV
	L2_TYPH_DSQ    = 0x0010 // TYPH.DSQ
	L2_TYPH_SSM    = 0x0003 // TYPH.SSM
	L2_UPDAT_      = 0x0003 // UPDAT.
	L2_V_DESC      = 0x0004 // V$DESC
	L2_V_DRIV      = 0x0000 // V$DRIV
	L2_V_DRIVEX    = 0x0009 // V$DRIVEX
	L2_V_FMGR      = 0x0006 // V$FMGR
	L2_V_FMGREX    = 0x000B // V$FMGREX
	L2_V_STAT      = 0x0002 // V$STAT
	L2_V_USRS      = 0x0008 // V$USRS
	L2_V_BMapSz    = 0x001C // V.BMapSz
	L2_V_BMB       = 0x0017 // V.BMB
	L2_V_BUSY      = 0x0004 // V.BUSY
	L2_V_DEV2      = 0x0009 // V.DEV2
	L2_V_DiskID    = 0x001A // V.DiskID
	L2_V_ERR       = 0x000E // V.ERR
	L2_V_FileHd    = 0x0018 // V.FileHd
	L2_V_INTR      = 0x000B // V.INTR
	L2_V_KANJI     = 0x0011 // V.KANJI
	L2_V_KBUF      = 0x0012 // V.KBUF
	L2_V_LINE      = 0x0007 // V.LINE
	L2_V_LPRC      = 0x0003 // V.LPRC
	L2_V_MapSct    = 0x001D // V.MapSct
	L2_V_MODADR    = 0x0014 // V.MODADR
	L2_V_NDRV      = 0x0006 // V.NDRV
	L2_V_PAGE      = 0x0000 // V.PAGE
	L2_V_PAUS      = 0x0008 // V.PAUS
	L2_V_PCHR      = 0x000D // V.PCHR
	L2_V_PDLHd     = 0x0016 // V.PDLHd
	L2_V_PORT      = 0x0001 // V.PORT
	L2_V_QUIT      = 0x000C // V.QUIT
	L2_V_ResBit    = 0x001E // V.ResBit
	L2_V_RSV       = 0x0018 // V.RSV
	L2_V_SCF       = 0x001D // V.SCF
	L2_V_ScOfst    = 0x0020 // V.ScOfst
	L2_V_ScTkOf    = 0x001F // V.ScTkOf
	L2_V_TkOfst    = 0x0021 // V.TkOfst
	L2_V_TRAK      = 0x0015 // V.TRAK
	L2_V_TYPE      = 0x0006 // V.TYPE
	L2_V_USER      = 0x0006 // V.USER
	L2_V_WAKE      = 0x0005 // V.WAKE
	L2_V_XOFF      = 0x0010 // V.XOFF
	L2_V_XON       = 0x000F // V.XON
	L2_VD_OFS      = 0x0061 // VD.OFS
	L2_VD_STP      = 0x0060 // VD.STP
	L2_Vi_Cnt      = 0x0000 // Vi.Cnt
	L2_Vi_IFlag    = 0x0001 // Vi.IFlag
	L2_Vi_PkSz     = 0x0005 // Vi.PkSz
	L2_Vi_Rst      = 0x0002 // Vi.Rst
	L2_Vi_Stat     = 0x0004 // Vi.Stat
	L2_WRITE_      = 0x0002 // WRITE.
	L2_XX_Size     = 0x0006 // XX.Size
)

var L2_SysCallNames = map[byte]string{
	L2_F_AProc:  "F$AProc",
	L2_F_AlHRAM: "F$AlHRAM",
	L2_F_Alarm:  "F$Alarm",
	L2_F_All64:  "F$All64",
	L2_F_AllBit: "F$AllBit",
	L2_F_AllImg: "F$AllImg",
	L2_F_AllPrc: "F$AllPrc",
	L2_F_AllRAM: "F$AllRAM",
	L2_F_AllTsk: "F$AllTsk",
	L2_F_Boot:   "F$Boot",
	L2_F_BtMem:  "F$BtMem",
	L2_F_CRC:    "F$CRC",
	L2_F_CRCMod: "F$CRCMod",
	L2_F_Chain:  "F$Chain",
	L2_F_ClrBlk: "F$ClrBlk",
	L2_F_CmpNam: "F$CmpNam",
	L2_F_CpyMem: "F$CpyMem",
	L2_F_DATLog: "F$DATLog",
	L2_F_DATTmp: "F$DATTmp",
	L2_F_Debug:  "F$Debug",
	L2_F_DelBit: "F$DelBit",
	L2_F_DelImg: "F$DelImg",
	L2_F_DelPrc: "F$DelPrc",
	L2_F_DelRAM: "F$DelRAM",
	L2_F_DelTsk: "F$DelTsk",
	L2_F_ELink:  "F$ELink",
	L2_F_Exit:   "F$Exit",
	L2_F_FModul: "F$FModul",
	L2_F_Find64: "F$Find64",
	L2_F_Fork:   "F$Fork",
	L2_F_FreeHB: "F$FreeHB",
	L2_F_FreeLB: "F$FreeLB",
	L2_F_GBlkMp: "F$GBlkMp",
	L2_F_GCMDir: "F$GCMDir",
	L2_F_GModDr: "F$GModDr",
	L2_F_GPrDsc: "F$GPrDsc",
	L2_F_GProcP: "F$GProcP",
	L2_F_ID:     "F$ID",
	L2_F_IODel:  "F$IODel",
	L2_F_IOQu:   "F$IOQu",
	L2_F_IRQ:    "F$IRQ",
	L2_F_Icpt:   "F$Icpt",
	L2_F_LDABX:  "F$LDABX",
	L2_F_LDAXY:  "F$LDAXY",
	L2_F_LDAXYP: "F$LDAXYP",
	L2_F_LDDDXY: "F$LDDDXY",
	L2_F_Link:   "F$Link",
	L2_F_Load:   "F$Load",
	L2_F_MapBlk: "F$MapBlk",
	L2_F_Mem:    "F$Mem",
	L2_F_Move:   "F$Move",
	L2_F_NMLink: "F$NMLink",
	L2_F_NMLoad: "F$NMLoad",
	L2_F_NProc:  "F$NProc",
	L2_F_NVRAM:  "F$NVRAM",
	L2_F_PErr:   "F$PErr",
	L2_F_PrsNam: "F$PrsNam",
	L2_F_ReBoot: "F$ReBoot",
	L2_F_RegDmp: "F$RegDmp",
	L2_F_RelTsk: "F$RelTsk",
	L2_F_ResTsk: "F$ResTsk",
	L2_F_Ret64:  "F$Ret64",
	L2_F_SLink:  "F$SLink",
	L2_F_SPrior: "F$SPrior",
	L2_F_SRqMem: "F$SRqMem",
	L2_F_SRtMem: "F$SRtMem",
	L2_F_SSWI:   "F$SSWI",
	L2_F_SSpd:   "F$SSpd",
	L2_F_SSvc:   "F$SSvc",
	L2_F_STABX:  "F$STABX",
	L2_F_STime:  "F$STime",
	L2_F_SUser:  "F$SUser",
	L2_F_SchBit: "F$SchBit",
	L2_F_Send:   "F$Send",
	L2_F_SetImg: "F$SetImg",
	L2_F_SetTsk: "F$SetTsk",
	L2_F_Sleep:  "F$Sleep",
	L2_F_TPS:    "F$TPS",
	L2_F_TimAlm: "F$TimAlm",
	L2_F_Time:   "F$Time",
	L2_F_UnLink: "F$UnLink",
	L2_F_UnLoad: "F$UnLoad",
	L2_F_VBlock: "F$VBlock",
	L2_F_VIRQ:   "F$VIRQ",
	L2_F_VModul: "F$VModul",
	L2_F_Wait:   "F$Wait",
	L2_F_XTime:  "F$XTime",
	L2_I_Attach: "I$Attach",
	L2_I_ChgDir: "I$ChgDir",
	L2_I_Close:  "I$Close",
	L2_I_Create: "I$Create",
	L2_I_DeletX: "I$DeletX",
	L2_I_Delete: "I$Delete",
	L2_I_Detach: "I$Detach",
	L2_I_Dup:    "I$Dup",
	L2_I_GetStt: "I$GetStt",
	L2_I_MakDir: "I$MakDir",
	L2_I_Open:   "I$Open",
	L2_I_Read:   "I$Read",
	L2_I_ReadLn: "I$ReadLn",
	L2_I_Seek:   "I$Seek",
	L2_I_SetStt: "I$SetStt",
	L2_I_WritLn: "I$WritLn",
	L2_I_Write:  "I$Write",
}

var L2_Slots_D = []Slot{
	{0x0000, "WDAddr"},
	{0x0002, "WDBtDr"},
	{0x0003, "SWPage"},
	{0x0009, "COCOXT"},
	{0x000a, "DbgMem"},
	{0x000c, "DWSubAddr"},
	{0x000e, "DWStat"},
	{0x0010, "DWSrvID"},
	{0x0020, "Tasks"},
	{0x0022, "TmpDAT"},
	{0x0024, "Init"},
	{0x0026, "Poll"},
	{0x0028, "Year"},
	{0x0029, "Month"},
	{0x002a, "Day"},
	{0x002b, "Hour"},
	{0x002c, "Min"},
	{0x002d, "Sec"},
	{0x002e, "Tick"},
	{0x002f, "Slice"},
	{0x0030, "TSlice"},
	{0x0031, "Boot"},
	{0x0032, "MotOn"},
	{0x0033, "ErrCod"},
	{0x0034, "Daywk"},
	{0x0035, "TkCnt"},
	{0x0036, "BtPtr"},
	{0x0038, "BtSz"},
	{0x003b, "CRC"},
	{0x003c, "Tenths"},
	{0x003d, "Task1N"},
	{0x003e, "Quick"},
	{0x003f, "QIRQ"},
	{0x0040, "BlkMap"},
	{0x0044, "ModDir"},
	{0x0048, "PrcDBT"},
	{0x004a, "SysPrc"},
	{0x004c, "SysDAT"},
	{0x004e, "SysMem"},
	{0x0050, "Proc"},
	{0x0052, "AProcQ"},
	{0x0054, "WProcQ"},
	{0x0056, "SProcQ"},
	{0x0058, "ModEnd"},
	{0x005a, "ModDAT"},
	{0x005c, "CldRes"},
	{0x005e, "BtBug"},
	{0x0061, "Pipe"},
	{0x006b, "Crash"},
	{0x0071, "CBStrt"},
	{0x007c, "QCnt"},
	{0x0080, "DevTbl"},
	{0x0082, "PolTbl"},
	{0x0088, "PthDBT"},
	{0x008a, "DMAReq"},
	{0x0090, "HINIT"},
	{0x0091, "TINIT"},
	{0x0092, "IRQER"},
	{0x0093, "FRQER"},
	{0x0094, "TIMMS"},
	{0x0095, "TIMLS"},
	{0x0096, "RESV1"},
	{0x0097, "RESV2"},
	{0x0098, "VIDMD"},
	{0x0099, "VIDRS"},
	{0x009a, "BORDR"},
	{0x009b, "RESV3"},
	{0x009c, "VOFF2"},
	{0x009d, "VOFF1"},
	{0x009e, "VOFF0"},
	{0x009f, "HOFF0"},
	{0x00a0, "Speed"},
	{0x00a1, "TskIPt"},
	{0x00a3, "MemSz"},
	{0x00a4, "SSTskN"},
	{0x00a5, "CCMem"},
	{0x00a7, "CCStk"},
	{0x00a9, "Flip0"},
	{0x00ab, "Flip1"},
	{0x00ad, "VIRQ"},
	{0x00af, "IRQS"},
	{0x00b0, "CLTb"},
	{0x00b2, "AltIRQ"},
	{0x00b4, "GPoll"},
	{0x00b6, "Clock2"},
	{0x00c0, "SysSvc"},
	{0x00c2, "SysDis"},
	{0x00c4, "SysIRQ"},
	{0x00c6, "UsrSvc"},
	{0x00c8, "UsrDis"},
	{0x00ca, "UsrIRQ"},
	{0x00cc, "SysStk"},
	{0x00ce, "SvcIRQ"},
	{0x00d0, "SysTsk"},
	{0x00e0, "Clock"},
	{0x00e2, "XSWI3"},
	{0x00e4, "XSWI2"},
	{0x00e6, "XFIRQ"},
	{0x00e8, "XIRQ"},
	{0x00ea, "XSWI"},
	{0x00ec, "XNMI"},
	{0x00ee, "ErrRst"},
	{0x00f0, "SysVec"},
	{0x00f2, "SWI3"},
	{0x00f4, "SWI2"},
	{0x00f6, "FIRQ"},
	{0x00f8, "IRQ"},
	{0x00fa, "SWI"},
	{0x00fc, "NMI"},
}
var L2_Slots_P = []Slot{
	{0x0000, "ID"},
	{0x0001, "PID"},
	{0x0002, "SID"},
	{0x0003, "CID"},
	{0x0004, "SP"},
	{0x0006, "Task"},
	{0x0007, "PagCnt"},
	{0x0008, "User"},
	{0x000a, "Prior"},
	{0x000b, "Age"},
	{0x000c, "State"},
	{0x000d, "Queue"},
	{0x000f, "IOQP"},
	{0x0010, "IOQN"},
	{0x0011, "PModul"},
	{0x0013, "SWI"},
	{0x0015, "SWI2"},
	{0x0017, "SWI3"},
	{0x0019, "Signal"},
	{0x001a, "SigVec"},
	{0x001c, "SigDat"},
	{0x001e, "DeadLk"},
	{0x0020, "DIO"},
	{0x0030, "Path"},
	{0x0040, "DATImg"},
	{0x0080, "Links"},
	{0x00a0, "NIO"},
	{0x00ac, "SelP"},
	{0x00ad, "UTicks"},
	{0x00b1, "STicks"},
	{0x00b5, "FCalls"},
	{0x00b9, "ICalls"},
	{0x00bd, "DatBeg"},
	{0x00c0, "TimBeg"},
	{0x00c3, "Alarm"},
}
var L2_Slots_PD = []Slot{
	{0x0000, "PD"},
	{0x0001, "MOD"},
	{0x0002, "CNT"},
	{0x0003, "DEV"},
	{0x0005, "CPR"},
	{0x0006, "RGS"},
	{0x0008, "BUF"},
	{0x000a, "SMF"},
	{0x000b, "CP"},
	{0x000c, "RAW"},
	{0x000d, "MAX"},
	{0x000f, "SIZ"},
	{0x0010, "STS"},
	{0x0012, "STM"},
	{0x0013, "SBL"},
	{0x0016, "SBP"},
	{0x0019, "SSZ"},
	{0x001c, "DSK"},
	{0x001e, "DTB"},
	{0x0020, "OPT"},
	{0x0021, "UPC"},
	{0x0022, "STP"},
	{0x0023, "TYP"},
	{0x0024, "EKO"},
	{0x0025, "CYL"},
	{0x0026, "NUL"},
	{0x0027, "SID"},
	{0x0028, "VFY"},
	{0x0029, "SCT"},
	{0x002a, "DEL"},
	{0x002b, "T0S"},
	{0x002c, "EOF"},
	{0x002d, "RPR"},
	{0x002e, "SAS"},
	{0x002f, "TFM"},
	{0x0030, "INT"},
	{0x0031, "QUT"},
	{0x0032, "SToff"},
	{0x0033, "OVF"},
	{0x0034, "PAR"},
	{0x0035, "BAU"},
	{0x0036, "D2P"},
	{0x0037, "DFD"},
	{0x0038, "XON"},
	{0x0039, "XOFF"},
	{0x003a, "ERR"},
	{0x003b, "TBL"},
	{0x003d, "PLP"},
	{0x003e, "DVT"},
	{0x003f, "PST"},
}
var L2_Os9Error = map[byte]string{
	L2_E_Alias:  "E$Alias",
	L2_E_ArrOvf: "E$ArrOvf",
	L2_E_BMCRC:  "E$BMCRC",
	L2_E_BMHP:   "E$BMHP",
	L2_E_BMID:   "E$BMID",
	L2_E_BMode:  "E$BMode",
	L2_E_BNam:   "E$BNam",
	L2_E_BPAddr: "E$BPAddr",
	L2_E_BPNam:  "E$BPNam",
	L2_E_BPNum:  "E$BPNum",
	L2_E_BPrcID: "E$BPrcID",
	L2_E_BTyp:   "E$BTyp",
	L2_E_BadBuf: "E$BadBuf",
	L2_E_BufSiz: "E$BufSiz",
	L2_E_Bug:    "E$Bug",
	L2_E_CEF:    "E$CEF",
	L2_E_CRC:    "E$CRC",
	L2_E_DIDC:   "E$DIDC",
	L2_E_DNE:    "E$DNE",
	L2_E_DeadLk: "E$DeadLk",
	L2_E_DelSP:  "E$DelSP",
	L2_E_DevBsy: "E$DevBsy",
	L2_E_DevOvf: "E$DevOvf",
	L2_E_DimLrg: "E$DimLrg",
	L2_E_DirFul: "E$DirFul",
	L2_E_DivZer: "E$DivZer",
	L2_E_Dn:     "E$Dn",
	L2_E_EOF:    "E$EOF",
	L2_E_EndQou: "E$EndQou",
	L2_E_ExcVrb: "E$ExcVrb",
	L2_E_FNA:    "E$FNA",
	L2_E_FltOvf: "E$FltOvf",
	L2_E_Full:   "E$Full",
	L2_E_HangUp: "E$HangUp",
	L2_E_IBA:    "E$IBA",
	L2_E_ICOvf:  "E$ICOvf",
	L2_E_IChRef: "E$IChRef",
	L2_E_ICoord: "E$ICoord",
	L2_E_IForkP: "E$IForkP",
	L2_E_IOConv: "E$IOConv",
	L2_E_IOFRpt: "E$IOFRpt",
	L2_E_IOFSyn: "E$IOFSyn",
	L2_E_IOMism: "E$IOMism",
	L2_E_IONum:  "E$IONum",
	L2_E_ISWI:   "E$ISWI",
	L2_E_IWDef:  "E$IWDef",
	L2_E_IWTyp:  "E$IWTyp",
	L2_E_IllA:   "E$IllA",
	L2_E_IllArg: "E$IllArg",
	L2_E_IllCmd: "E$IllCmd",
	L2_E_IllCnt: "E$IllCnt",
	L2_E_IllDec: "E$IllDec",
	L2_E_IllDim: "E$IllDim",
	L2_E_IllExp: "E$IllExp",
	L2_E_IllFOR: "E$IllFOR",
	L2_E_IllIVr: "E$IllIVr",
	L2_E_IllInp: "E$IllInp",
	L2_E_IllLit: "E$IllLit",
	L2_E_IllMod: "E$IllMod",
	L2_E_IllNum: "E$IllNum",
	L2_E_IllOpd: "E$IllOpd",
	L2_E_IllOpr: "E$IllOpr",
	L2_E_IllPNm: "E$IllPNm",
	L2_E_IllPrf: "E$IllPrf",
	L2_E_IllRFN: "E$IllRFN",
	L2_E_IllRet: "E$IllRet",
	L2_E_IllSfx: "E$IllSfx",
	L2_E_IllStC: "E$IllStC",
	L2_E_KwnMod: "E$KwnMod",
	L2_E_LinLrg: "E$LinLrg",
	L2_E_LnComp: "E$LnComp",
	L2_E_Lock:   "E$Lock",
	L2_E_MFull:  "E$MFull",
	L2_E_MNF:    "E$MNF",
	L2_E_MemFul: "E$MemFul",
	L2_E_MltLin: "E$MltLin",
	L2_E_MltVar: "E$MltVar",
	L2_E_ModBsy: "E$ModBsy",
	L2_E_MulPrc: "E$MulPrc",
	L2_E_NEMod:  "E$NEMod",
	L2_E_NES:    "E$NES",
	L2_E_NFont:  "E$NFont",
	L2_E_NoAssg: "E$NoAssg",
	L2_E_NoChld: "E$NoChld",
	L2_E_NoComa: "E$NoComa",
	L2_E_NoDO:   "E$NoDO",
	L2_E_NoData: "E$NoData",
	L2_E_NoDim:  "E$NoDim",
	L2_E_NoGoto: "E$NoGoto",
	L2_E_NoLPar: "E$NoLPar",
	L2_E_NoLRef: "E$NoLRef",
	L2_E_NoOprd: "E$NoOprd",
	L2_E_NoPath: "E$NoPath",
	L2_E_NoRAM:  "E$NoRAM",
	L2_E_NoRPar: "E$NoRPar",
	L2_E_NoRout: "E$NoRout",
	L2_E_NoTHEN: "E$NoTHEN",
	L2_E_NoTO:   "E$NoTO",
	L2_E_NoTask: "E$NoTask",
	L2_E_NoVRef: "E$NoVRef",
	L2_E_NonRcO: "E$NonRcO",
	L2_E_NotRdy: "E$NotRdy",
	L2_E_PNNF:   "E$PNNF",
	L2_E_ParmEr: "E$ParmEr",
	L2_E_Poll:   "E$Poll",
	L2_E_PrcAbt: "E$PrcAbt",
	L2_E_PrcFul: "E$PrcFul",
	L2_E_PthFul: "E$PthFul",
	L2_E_Read:   "E$Read",
	L2_E_SLF:    "E$SLF",
	L2_E_Sect:   "E$Sect",
	L2_E_Seek:   "E$Seek",
	L2_E_SeekRg: "E$SeekRg",
	L2_E_Share:  "E$Share",
	L2_E_StkOvf: "E$StkOvf",
	L2_E_StrOvf: "E$StrOvf",
	L2_E_SubLrg: "E$SubLrg",
	L2_E_SubOvf: "E$SubOvf",
	L2_E_SubRng: "E$SubRng",
	L2_E_SubUnd: "E$SubUnd",
	L2_E_SysOvf: "E$SysOvf",
	L2_E_TblFul: "E$TblFul",
	L2_E_TypMis: "E$TypMis",
	L2_E_USigP:  "E$USigP",
	L2_E_UndLin: "E$UndLin",
	L2_E_UndVar: "E$UndVar",
	L2_E_Unit:   "E$Unit",
	L2_E_UnkPrc: "E$UnkPrc",
	L2_E_UnkSvc: "E$UnkSvc",
	L2_E_UnkSym: "E$UnkSym",
	L2_E_UnmCnt: "E$UnmCnt",
	L2_E_Up:     "E$Up",
	L2_E_ValRng: "E$ValRng",
	L2_E_WADef:  "E$WADef",
	L2_E_WP:     "E$WP",
	L2_E_WUndef: "E$WUndef",
	L2_E_WrSub:  "E$WrSub",
	L2_E_Write:  "E$Write",
}
var L2_Os9ErrorName = map[byte]string{
	183: "Illegal window type",
	184: "Window already defined",
	185: "Font Not found",
	186: "Stack Overflow",
	187: "Illegal Argument",
	188: "unused",
	189: "Illegal Coordinates",
	190: "Internal Integrity check",
	191: "Buffer size is too small",
	192: "Illegal Command",
	193: "Screen or Window Table is Full",
	194: "Bad/Undefined buffer number",
	195: "Illegal window definition",
	196: "Window undefined",
	197: "unused",
	198: "unused",
	199: "unused",
	200: "Path Table Full",
	201: "Illegal Path Number",
	202: "Interrupt Polling Table Full",
	203: "Illegal Mode",
	204: "Device Table Full",
	205: "Illegal Module Header",
	206: "Module Directory Full",
	207: "Memory Full",
	208: "Illegal Service Request",
	209: "Module Busy",
	210: "Boundary Error",
	211: "End of File",
	212: "Returning non-allocated memory",
	213: "Non-existing Segment",
	214: "No Permission",
	215: "Bad Path Name",
	216: "Path Name Not Found",
	217: "Segment List Full",
	218: "File Already Exists",
	219: "Illegal Block Address",
	220: "Phone Hangup-Data Carrier Detect lost",
	221: "Module Not Found",
	223: "Suicide Attempt",
	224: "Illegal Process Number",
	226: "No Children",
	227: "Illegal SWI Code",
	228: "Process Aborted",
	229: "Process Table Full",
	230: "Illegal Parameter Area",
	231: "Known module",
	232: "Incorrect Module CRC",
	233: "Signal Error",
	234: "Non-existent Module",
	235: "Bad Name",
	236: "Bad Module Header",
	237: "RAM Full",
	238: "Unknown Process ID",
	239: "No task number available",
	240: "Unit Error",
	241: "Sector Error",
	242: "Write Protect",
	243: "CRC Error",
	244: "Read Error",
	245: "Write Error",
	246: "Not Ready",
	247: "Seek Error",
	248: "Media Full",
	249: "Wrong Type",
	250: "Device Busy",
	251: "Disk ID Change",
	252: "Record is locked-out",
	253: "Non-sharable file busy",
	254: "I/O Deadlock Error",
	1:   "Unconditional Abort",
	2:   "Keyboard Abort",
	3:   "Keyboard Interrupt",
	10:  "Unrecognized Symbol",
	11:  "Excessive Verbage",
	12:  "Illegal Statement Construction",
	13:  "I-code Overflow",
	14:  "Illegal Channel Reference",
	15:  "Illegal Mode (read/write/update)",
	16:  "Illegal Number",
	17:  "Illegal Prefix",
	18:  "Illegal Operand",
	19:  "Illegal Operator",
	20:  "Illegal Record Field Name",
	21:  "Illegal Dimension",
	22:  "Illegal Literal",
	23:  "Illegal Relational",
	24:  "Illegal Type Suffix",
	25:  "Too-large Dimension",
	26:  "Too-large Line Number",
	27:  "Missing Assignment Statement",
	28:  "Missing Path Number",
	29:  "Missing Comma",
	30:  "Missing Dimension",
	31:  "Missing DO Statement",
	32:  "Memory Full",
	33:  "Missing GOTO",
	34:  "Missing Left Parenthesis",
	35:  "Missing Line Reference",
	36:  "Missing Operand",
	37:  "Missing Right Parenthesis",
	38:  "Missing THEN statement",
	39:  "Missing TO",
	40:  "Missing Variable Reference",
	41:  "No Ending Quote",
	42:  "Too Many Subscripts",
	43:  "Unknown Procedure",
	44:  "Multiply-defined Procedure",
	45:  "Divide by Zero",
	46:  "Operand Type Mismatch",
	47:  "String Stack Overflow",
	48:  "Unimplemented Routine",
	49:  "Undefined Variable",
	50:  "Floating Overflow",
	51:  "Line with Compiler Error",
	52:  "Value out of Range for Destination",
	53:  "Subroutine Stack Overflow",
	54:  "Subroutine Stack Underflow",
	55:  "Subscript out of Range",
	56:  "Parameter Error",
	57:  "System Stack Overflow",
	58:  "I/O Type Mismatch",
	59:  "I/O Numeric Input Format Bad",
	60:  "I/O Conversion: Number out of Range",
	61:  "Illegal Input Format",
	62:  "I/O Format Repeat Error",
	63:  "I/O Format Syntax Error",
	64:  "Illegal Path Number",
	65:  "Wrong Number of Subscripts",
	66:  "Non-record-type Operand",
	67:  "Illegal Argument",
	68:  "Illegal Control Structure",
	69:  "Unmatched Control Structure",
	70:  "Illegal FOR Variable",
	71:  "Illegal Expression Type",
	72:  "Illegal Declarative Statement",
	73:  "Array Size Overflow",
	74:  "Undefined Line Number",
	75:  "Multiply-defined Line Number",
	76:  "Multiply-defined Variable",
	77:  "Illegal Input Variable",
	78:  "Seek Out of Range",
	79:  "Missing Data Statement",
}
