#ifndef _TFR9_V3_APPS_T9SIM_H_
#define _TFR9_V3_APPS_T9SIM_H_

#define T9SIM_BASE_ADDR 0xFF00

#define T9SIM_TX_ADDR (T9SIM_BASE_ADDR + 0)
#define T9SIM_RX_ADDR (T9SIM_BASE_ADDR + 1)
#define T9SIM_STATUS_ADDR (T9SIM_BASE_ADDR + 2)
#define T9SIM_CONTROL_ADDR (T9SIM_BASE_ADDR + 3)

#define T9SIM_TIMER_BIT 0x01
#define T9SIM_RX_BIT 0x02

#endif  // _TFR9_V3_APPS_T9SIM_H_
