// v4_centipede_main.cpp — Centipede v4 build: wires v4 framework + v1 code.
//
// This is the top-level compilation unit for the Centipede v4 firmware.
// It includes:
//   - v4 framework headers (types, RAM, interrupts, engine)
//   - v4 compatibility shim (maps v1 naming to v4)
//   - v1 implementation headers (coco64k, disk11_rom, floppy, gspoon, etc.)
//
// The v4 Engine struct composes CRTP mixins from both v4 (CentipedeEngine)
// and v1 (DoCoco64k, DoFloppy). The foreground and background loops are
// ported from v1's CoreEngine with minimal changes.
//
// Build: cmake with PLATFORM=CENTIPEDE, CENTIPEDE_REV=3205.

// ═══════════════════════════════════════════════════════════════════
// Pico SDK headers
// ═══════════════════════════════════════════════════════════════════
#include <pico/stdlib.h>
#include <pico/multicore.h>
#include <hardware/pio.h>
#include <hardware/gpio.h>
#include <hardware/sync.h>
#include <hardware/structs/sio.h>
#include <hardware/structs/qmi.h>

#include <array>
#include <atomic>
#include <cstdint>
#include <functional>
#include <string>

// ═══════════════════════════════════════════════════════════════════
// v4 framework headers (types, enums, macros)
// ═══════════════════════════════════════════════════════════════════
#include "v4_types.h"
#include "v4_ram.h"
#include "v4_interrupts.h"
#include "v4_turbo9sim.h"
#include "v4_trace.h"
#include "v4_os_loader.h"
#include "v4_engine_centipede.h"
// NOTE: v4_core_engine.h is included by v4_engine_centipede.h.
// NOTE: v4_floppy.h and v4_console.h are NOT used — we use v1's versions.

// ═══════════════════════════════════════════════════════════════════
// v4 compatibility shim — bridges v1 naming to v4
// ═══════════════════════════════════════════════════════════════════
#include "v4_compat_centipede.h"

// ═══════════════════════════════════════════════════════════════════
// Global storage (BSS — always in RAM)
// ═══════════════════════════════════════════════════════════════════
byte ram[64 * 1024];
IOReader IOReaders[256];
IOWriter IOWriters[256];
byte vector_ram[16];

// ═══════════════════════════════════════════════════════════════════
// Tcl interpreter (shared global, used by gspoon + tcl_commands)
// ═══════════════════════════════════════════════════════════════════
#include "../v1/tcl6.7c/tcl.h"
Tcl_Interp* global_tcl_interp = nullptr;

// ═══════════════════════════════════════════════════════════════════
// USB pipeline and COBS infrastructure
// ═══════════════════════════════════════════════════════════════════
CircBuf<unsigned char, 1024> usb_raw_buf;
CircBuf<std::string*, 64> usb_packet_buf;

#include "../v1/firmware/usb_pipeline.h"

UsbReceiver usb_receiver(usb_raw_buf);
CobsDecoder<1024, 64> cobs_decoder(usb_raw_buf, usb_packet_buf);

// ═══════════════════════════════════════════════════════════════════
// COBS TX helpers
// ═══════════════════════════════════════════════════════════════════
#define INCLUDING
#include "../v1/firmware/cobs_tx.h"

// ═══════════════════════════════════════════════════════════════════
// Gerbil PIO (generated header from .pio file)
// ═══════════════════════════════════════════════════════════════════
#include "gerbil.pio.h"  // Generated by pioasm during cmake build.

#define GERBIL_GET() gerbil_program_get_word(pio, sm)
#define GERBIL_DRIVE(X) gerbil_program_put_word(pio, sm, 0x100 | (X))
#define GERBIL_PASS() gerbil_program_put_word(pio, sm, 0)

// ═══════════════════════════════════════════════════════════════════
// ROM data
// ═══════════════════════════════════════════════════════════════════
#include "../v1/firmware/bug.h"
#include "../v1/firmware/disk11_rom.h"
#include "../v1/firmware/egg.h"

// ═══════════════════════════════════════════════════════════════════
// Code constants
// ═══════════════════════════════════════════════════════════════════
const char HexAlphabet[] =
    "0123456789ABCDEFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    "XXXXXXX";

// Speed / Flow control constants
#ifndef SLOW_SPEED
#define SLOW_SPEED 3
#endif
#ifndef MEDIUM_SPEED
#define MEDIUM_SPEED 2
#endif
#ifndef FAST_SPEED
#define FAST_SPEED 1
#endif
volatile uint Speed = SLOW_SPEED;

// Counter for push failures and writes (used by PushFifoWrite)
volatile uint push_fail_counter = 0;
volatile uint write_counter = 0;

// ═══════════════════════════════════════════════════════════════════
// Spoon task work flag (used by drain_task/spoon_task/foreground)
// ═══════════════════════════════════════════════════════════════════
volatile bool spoon_has_work = false;

// ═══════════════════════════════════════════════════════════════════
// Coroutine support
// ═══════════════════════════════════════════════════════════════════
#include "../v1/firmware/coro.h"
#define STACK_SIZE 4096

// ═══════════════════════════════════════════════════════════════════
// LittleFS / VFS
// ═══════════════════════════════════════════════════════════════════
#include "../v1/firmware/vfs.h"
#include "../v1/firmware/littlefs.h"

// ═══════════════════════════════════════════════════════════════════
// Flash label (board identification in flash)
// ═══════════════════════════════════════════════════════════════════
#include "../v1/firmware/flash_label.h"

// ═══════════════════════════════════════════════════════════════════
// 20ms timer (for Turbo9sim timer IRQ — not used by Centipede
// but needed for gspoon's RTC support)
// ═══════════════════════════════════════════════════════════════════
#include "../v1/firmware/rtc.h"

// ═══════════════════════════════════════════════════════════════════
// Console and keyboard
// ═══════════════════════════════════════════════════════════════════
#include "../v1/firmware/console.h"
#include "../v1/firmware/keyboard_injector.h"

// ═══════════════════════════════════════════════════════════════════
// v1 CRTP mixins (these are the real implementations)
// ═══════════════════════════════════════════════════════════════════
#include "../v1/firmware/coco64k.h"

// Floppy: use VFS-based I/O for /pc/floppy0.dsk
#define FLOPPY_OVER_VFS 1
#include "../v1/firmware/floppy.h"

// ═══════════════════════════════════════════════════════════════════
// Tcl commands and gspoon (console/spoonfeeder)
// ═══════════════════════════════════════════════════════════════════
#include "../v1/firmware/tcl_io.h"
#include "../v1/firmware/tcl_commands.h"
#include "../v1/firmware/pcb.h"
#include "../v1/firmware/pico_rpc.h"
#include "../v1/firmware/gspoon.h"

// ═══════════════════════════════════════════════════════════════════
// Compressed cycle support
// ═══════════════════════════════════════════════════════════════════
#ifndef COMPRESS_CYCLES
#define COMPRESS_CYCLES 0
#endif
#if COMPRESS_CYCLES
#include "../v1/firmware/compress_cycles.h"
#endif
inline void ResetCompressCycles() {
#if COMPRESS_CYCLES
  // Reset compression state
#endif
}
#if COMPRESS_CYCLES
inline void InsertCycleWithCompression(uint chore) {
  // Stub — full implementation in compress_cycles.h
}
inline void FlushPartialCycleBuffer() {
  // Stub
}
#endif

// ═══════════════════════════════════════════════════════════════════
// rp2350_reset_standard — restart into standard (non-flash) mode
// ═══════════════════════════════════════════════════════════════════
void rp2350_reset_standard(void) {
  // Set flag for standard boot mode
  boot_mode = 0;
  boot_mode_check = BOOT_MODE_CHECKER;
  // Software reset
  watchdog_reboot(0, 0, 0);
  while (true) tight_loop_contents();
}

// ═══════════════════════════════════════════════════════════════════
// The Engine — composes v4 infrastructure + v1 CRTP mixins
// ═══════════════════════════════════════════════════════════════════
//
// v4 provides: CentipedeEngine (GPIO, pin control, flow control)
// v1 provides: DoCoco64k, DoFloppy (the real implementations)
//
// Forward declarations for trampolines
void IN_RAM core1_trampoline();
void IN_RAM core0_trampoline();

// The v1 CoreEngine contains the foreground loop, background scheduler,
// coroutine tasks, and RunCores/RunEngine. We use it directly.
// The v4 CentipedeEngine is NOT mixed in here — we use v1's CoreEngine
// which contains the equivalent functionality (InitializePins, etc.)
// already wired for the v1 code paths.
//
// TODO: In the future, refactor v1's CoreEngine to delegate to v4's
// CentipedeEngine for pin control, flow control, etc.
#include "../v1/firmware/centipede_core_engine.h"
// NOTE: centipede_core_engine.h does not exist yet — see below.
// For now we include the relevant portions inline.

// Since v1's CoreEngine is defined inside centipede.cpp (not a header),
// and extracting it cleanly requires careful surgery, we define the
// Engine composition here using v1's existing CRTP templates.

// ── v1-style CoreEngine (adapted for v4 context) ──
// This is extracted from v1/firmware/centipede.cpp lines 536-1004.
// It provides: foreground loop, background scheduler, coroutine tasks,
// InitializePins, RunCores.

template <class T>
class V4CoreEngine {
 public:
  static void IN_RAM Fatal(const char* s, int x) {
    cobs_printf("\nFATAL(%d.): %s\n", x, s);
    while (1) continue;
  }

  static void IN_FLASH InitializePins() {
    for (uint i = 0; i <= 22; i++) {
      gpio_init(i);
      gpio_set_dir(i, GPIO_IN);
      gpio_set_pulls(i, false, false);
    }
    OUTPUT(G_LED, 1);
    INPUT(G_SND);
    INPUT(G_CTS);
    INPUT(G_SCS);
    INPUT(G_RESET);
    INPUT(G_SLENB);

    OPEN_DRAIN(G_HALT);
    OPEN_DRAIN(G_NMI);
    OPEN_DRAIN(G_CART);

    for (uint i = 32; i <= 47; i++) {
      gpio_init(i);
      gpio_set_dir(i, GPIO_IN);
      gpio_set_pulls(i, false, false);
    }
    gpio_init(G_LED);
    gpio_set_dir(G_LED, GPIO_OUT);
    SET_LED(0);
  }

  // Coroutine stacks
  static inline uint8_t drain_stack[STACK_SIZE] __attribute__((aligned(8)));
  static inline uint8_t floppy_stack[STACK_SIZE] __attribute__((aligned(8)));
  static inline uint8_t spoon_stack[STACK_SIZE] __attribute__((aligned(8)));

  // Floppy task channel
  static inline volatile uint floppy_pending_chore;
  static inline volatile bool floppy_has_work;

  // ── drain_task ──
  static void drain_task(Coro& self) {
    while (true) {
      if (nmi_pending) {
        nmi_pending = false;
        gpio_set_dir(G_NMI, GPIO_IN);
      }

      keyboard_injector::tick();

      uint chore = 0;
      if (!fg2bg.pop(chore)) {
#if COMPRESS_CYCLES
        FlushPartialCycleBuffer();
#endif
        coro_yield(&self);
        continue;
      }

      const uint chore_num = chore >> 24;
      const byte chore_byte = 0xFF & chore;

      switch (chore_num) {
        case FG2BG_PUTCHAR:
          if (chore_byte) cobs_putchar(chore_byte);
          break;
        case FG2BG_START_KEYBOARD_INJECTOR:
          keyboard_injector::start_if_queued();
          break;
        case FG2BG_READ:
#if COMPRESS_CYCLES
          InsertCycleWithCompression(chore);
#else
          if (chore_byte && usb_tether_ok()) {
            unsigned char pkt[4] = {C_RAM2_WRITE,  // Actually C_RAM2_READ
                                    (unsigned char)(chore >> 16),
                                    (unsigned char)(chore >> 8),
                                    (unsigned char)chore};
            CobsEncodeAndTransmit(pkt, 4, putchar_raw);
          }
#endif
          break;
        case FG2BG_WRITE:
          write_counter++;
#if COMPRESS_CYCLES
          InsertCycleWithCompression(chore);
#else
          if (usb_tether_ok()) {
            unsigned char pkt[4] = {C_RAM2_WRITE,
                                    (unsigned char)(chore >> 16),
                                    (unsigned char)(chore >> 8),
                                    (unsigned char)chore};
            CobsEncodeAndTransmit(pkt, 4, putchar_raw);
          }
#endif
          break;
        case FG2BG_NMI:
          break;
        case FG2BG_FLOPPY_LATCH:
        case FG2BG_FLOPPY_COMMAND:
        case FG2BG_W_256:
          while (floppy_has_work) coro_yield(&self);
          floppy_pending_chore = chore;
          floppy_has_work = true;
          break;
        case FG2BG_SPOON_ON_RESET:
          spoon_has_work = true;
          break;
        case FG2BG_PEEK_REPLY:
          break;
        default:
          cobs_printf("\nWUT? CHORE=%x\n", chore);
      }
      coro_yield(&self);
    }
  }

  // ── floppy_task ──
  static void floppy_task(Coro& self) {
    while (true) {
      if (!floppy_has_work) { coro_yield(&self); continue; }
      uint chore = floppy_pending_chore;
      uint chore_num = chore >> 24;
      byte chore_byte = chore & 0xFF;
      switch (chore_num) {
        case FG2BG_FLOPPY_LATCH:
          T::BackgroundFifoFloppyLatch(chore_byte);
          break;
        case FG2BG_FLOPPY_COMMAND:
          T::BackgroundFifoFloppyCommand(self, chore, chore_byte);
          break;
        case FG2BG_W_256:
          T::BackgroundFifoFloppyW256(self);
          break;
      }
      floppy_has_work = false;
    }
  }

  // ── spoon_task ──
  static void spoon_task(Coro& self) {
    while (true) {
      if (!spoon_has_work) { coro_yield(&self); continue; }
      HaltOff();
      gspoon::BackgroundSpoonFeeder(&self);
      spoon_has_work = false;
    }
  }

  // ── background ──
  FORCE_INLINE static void background() {
    Coro drain, floppy, spoon;
    coro_create(&drain, drain_task, drain_stack, sizeof(drain_stack));
    coro_create(&floppy, floppy_task, floppy_stack, sizeof(floppy_stack));
    coro_create(&spoon, spoon_task, spoon_stack, sizeof(spoon_stack));
    cobs_printf("Background: coroutines initialized.\n");

    while (true) {
      coro_resume(&drain);
      if (PumpUsbCobsHasWork()) PumpUsbCobs();
      coro_resume(&floppy);
      if (PumpUsbCobsHasWork()) PumpUsbCobs();
      coro_resume(&spoon);
      if (PumpUsbCobsHasWork()) PumpUsbCobs();
    }
  }

  // ── foreground ──
  FORCE_INLINE static void foreground() {
    save_and_disable_interrupts();
    const PIO pio = pio0;
    constexpr uint sm = 0;

    if (!detect_e_clock()) {
      cobs_printf(" [-E] ");
      spoon_has_work = true;
      while (!detect_e_clock()) {
        for (volatile uint i = 0; i < 2500000; i++) {}
      }
      cobs_printf(" [+E] ");
    }

    gspoon::SpoonfeedConsoleOnReset();
    PUSH_TO_BG(FG2BG_START_KEYBOARD_INJECTOR, 0, 0);

    uint cycle = 0;
    bool floppy_emulation = centipede_config.floppy_fd || centipede_config.floppy_pc;
    while (true) {
      const uint signals = GERBIL_GET();
      FlowControlCheck();

      const bool reading = ((signals & (1u << G_RW)) != 0);
      const uint abus = volatile_sio_hw->gpio_hi_in & 0xFFFF;
      byte dbus = 0x00;

      constexpr uint NEG_CTS = (1 << G_CTS);
      constexpr uint NEG_SCS = (1 << G_SCS);
      constexpr uint NEG_SELECTS = NEG_CTS | NEG_SCS;

      if (LIKELY(!floppy_emulation || (signals & NEG_SELECTS) == NEG_SELECTS)) {
        if (LIKELY(reading)) {
          if (0xFF00 <= abus) {
            if (UNLIKELY(abus == 0xFF00 && keyboard_injector::active)) {
              byte probe = ram[0xFF02];
              byte sense = 0x7F;
              for (int col = 0; col < 8; col++) {
                if ((probe & (1 << col)) == 0) {
                  sense &= keyboard_injector::row_response[col];
                }
              }
              dbus = sense;
              GERBIL_DRIVE(dbus);
            } else {
              auto r = IOReaders[abus & 0xFF];
              if (r) {
                dbus = r(abus);
                GERBIL_DRIVE(dbus);
              } else {
                GERBIL_PASS();
                dbus = (byte)(GERBIL_GET());
              }
            }
          } else if (centipede_config.rom_disk11
                     && not T::UseCoco64kRam(abus)
                     && 0xC000 <= abus && abus < 0xE000) {
            dbus = disk11_rom[abus & 0x1FFF];
            GERBIL_DRIVE(dbus);
          } else if (centipede_config.ram_64k && T::UseCoco64kRam(abus)) {
            uint atrans = T::TranslateCoco64kRamAddress(abus);
            dbus = ram[atrans];
            GERBIL_DRIVE(dbus);
          } else {
            GERBIL_PASS();
            dbus = (byte)(GERBIL_GET());
          }
          if (centipede_config.trace_reads
              || (centipede_config.trace_writes && 0xFF00 <= abus)) {
            T::PushFifoRead(abus, dbus);
          }
        } else {
          dbus = (byte)(GERBIL_GET());
          if (0xFF00 <= abus) {
            auto w = IOWriters[abus & 0xFF];
            if (w) w(abus, dbus);
            ram[abus] = dbus;
            T::PushFifoWrite(abus, dbus);
          } else {
            uint atrans = T::UseCoco64kRam(abus)
                              ? T::TranslateCoco64kRamAddress(abus)
                              : abus;
            ram[atrans] = dbus;
            if (centipede_config.trace_writes) {
              T::PushFifoWrite(atrans, dbus);
            }
          }
        }
      } else {
        if (LIKELY(reading)) {
          if ((signals & NEG_SCS) == 0) {
            T::ReadScsFloppy(abus, dbus);
          }
          GERBIL_DRIVE(dbus);
          if (true) T::PushFifoRead(abus, dbus);
        } else {
          dbus = (byte)(GERBIL_GET());
          ram[abus] = dbus;
          if (LIKELY((signals & NEG_SCS) == 0)) {
            T::WriteScsFloppy(abus, dbus);
          }
          T::PushFifoWrite(abus, dbus);
        }
      }

      ++cycle;

#if ON_RESET_DO_SPOONFEED_CONSOLE
      if ((signals & (1 << G_RESET)) == 0) break;
#endif
    }  // end while true

    rp2350_reset_standard();
  }  // end foreground

  FORCE_INLINE static void PushFifoRead(uint abus, byte dbus) {
    if (abus != 0xFFFF) {
      PUSH_TO_BG(FG2BG_READ, abus, dbus);
    }
  }

  FORCE_INLINE static void PushFifoWrite(uint abus, byte dbus) {
    if (Speed <= MEDIUM_SPEED) {
      bool ok = fg2bg.push(((FG2BG_WRITE) << 24) | ((abus) << 8) | (dbus));
      if (!ok) push_fail_counter++;
    }
  }

  FORCE_INLINE static void RunCores(void (*core1_func)(void),
                                    void (*core0_func)(void)) {
    const PIO pio = pio0;
    constexpr uint sm = 0;

    pio_clear_instruction_memory(pio);
    pio_add_program_at_offset(pio, &gerbil_program, 0);
    gerbil_program_init(pio, sm, 0);
    cobs_printf("#gerbil_program.length=%d\n", gerbil_program.length);

    multicore_launch_core1(core1_func);
    core0_func();
  }
};

// OPEN_DRAIN macro (used by InitializePins)
#ifndef OPEN_DRAIN
#define OPEN_DRAIN(PIN)        \
  gpio_init(PIN);              \
  gpio_set_dir(PIN, GPIO_OUT); \
  gpio_put(PIN, 0);            \
  gpio_set_dir(PIN, GPIO_IN);  \
  gpio_set_pulls(PIN, true, false);
#endif

#ifndef ON_RESET_DO_SPOONFEED_CONSOLE
#define ON_RESET_DO_SPOONFEED_CONSOLE 1
#endif

// ═══════════════════════════════════════════════════════════════════
// Engine composition
// ═══════════════════════════════════════════════════════════════════
class Engine : public DoFloppy<Engine>,
               public DoCoco64k<Engine>,
               public V4CoreEngine<Engine> {
 public:
  static void RunEngine() {
    InitCoco64k();
    ResetCompressCycles();
    RunCores(core1_trampoline, core0_trampoline);
  }
};

void IN_RAM core1_trampoline() { Engine::foreground(); }
void IN_RAM core0_trampoline() { Engine::background(); }

// ═══════════════════════════════════════════════════════════════════
// safe_adjust_flash_speed
// ═══════════════════════════════════════════════════════════════════
#ifndef MHz
#define MHz 250
#endif

void IN_RAM safe_adjust_flash_speed() {
#if MHz > 150
  uint32_t ints = save_and_disable_interrupts();
  const uint32_t SAFE = 4;
  uint32_t clkdiv = SAFE;
  uint32_t rxdelay = 4;
  hw_write_masked(
      &qmi_hw->m[0].timing,
      ((clkdiv << QMI_M0_TIMING_CLKDIV_LSB) & QMI_M0_TIMING_CLKDIV_BITS) |
          ((rxdelay << QMI_M0_TIMING_RXDELAY_LSB) & QMI_M0_TIMING_RXDELAY_BITS),
      QMI_M0_TIMING_CLKDIV_BITS | QMI_M0_TIMING_RXDELAY_BITS);
  restore_interrupts(ints);
#endif
}

// ═══════════════════════════════════════════════════════════════════
// main
// ═══════════════════════════════════════════════════════════════════
int IN_RAM main() {
  Engine::InitializePins();
  FlashLabel::InitLabel();
#if MHz != 150
  set_sys_clock_khz(MHz * 1000, true);
#endif
  stdio_usb_init();
  safe_adjust_flash_speed();

  OUTPUT(G_HALT, 0);
  OUTPUT(G_RESET, 0);
  for (uint i = 0; i < 5; i++) {
    SET_LED(1); sleep_ms(200);
    SET_LED(0); sleep_ms(200);
  }
  INPUT(G_RESET);
  INPUT(G_HALT);

  FlashLabel::PrintLabel();
  init_lfs();
  start_20ms_timer();
  global_tcl_interp = Tcl_CreateInterp();
  register_tcl_commands(global_tcl_interp);
  centipede_config.SetAll(true);
  centipede_config.trace_reads = false;
  centipede_config.floppy_pc = false;
  set_floppy_names();

  Engine::RunEngine();
}
